### ISSUE TITLE
could somebody please add tags and add archives for total-connect-client-0.57?

### ISSUE THREAD

**Issue by onkelbeh** [craigjmidwinter/total-connect-client#109]
could somebody please add tags and add archives for total-connect-client-0.57?
Please also add these to Pypi.

**Comment by austinmroczek** [comment]
If by archive you mean `tar.gz` file, it is already in pypi if you look at https://pypi.org/project/total-connect-client/0.57/#files.  

Sorry the tagging of releases hasn't been consistent.  I just tagged 0.58.
