### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable when retrieve zone data

### ISSUE THREAD

**Issue by jcarr** [craigjmidwinter/total-connect-client#112]
Recently had this working fine although it's no longer working.  I had a tech out to switch out the cellular modem on my security unit and started having problems.  Ran with a fully prived account with the same result.

```Traceback (most recent call last):
  File "info.py", line 18, in <module>
    TC = TotalConnectClient.TotalConnectClient(USERNAME, PASSWORD)
  File "/home/jason/TotalConnectClient.py", line 96, in __init__
    self.authenticate()
  File "/home/jason/TotalConnectClient.py", line 214, in authenticate
    self.populate_details(response)
  File "/home/jason/TotalConnectClient.py", line 302, in populate_details
    self.get_panel_meta_data(location_id)
  File "/home/jason/TotalConnectClient.py", line 432, in get_panel_meta_data
    status = self.locations[location_id].set_status(
  File "/home/jason/TotalConnectClient.py", line 646, in set_status
    if "ZoneInfo" not in data["Zones"]:
  TypeError: argument of type 'NoneType' is not iterable```

**Comment by austinmroczek** [comment]
This was recently working via the standalone code, or as part of Home Assistant?

**Comment by jcarr** [comment]
It was working in Home Assistant. This output was from the standalone code
while I was trying to figure out the problem.

**Comment by austinmroczek** [comment]
I'll work on it later tonight.  

Not absolutely necessary but if the error message from Home Assistant is handy please post here too

**Comment by austinmroczek** [comment]
@jcarr 

Sorry I just realized we had a pull request that wasn't added to master yet.  There were some code updates in there that (a) definitely changed all the line numbers so helping debug is harder and (b) might have fixed your problem.  

Please download the latest code again (as described in Troubleshooting) and run info.py again.

**Comment by jcarr** [comment]
I did a fresh wget and here is the output:
```Traceback (most recent call last):  File "info.py", line 18, in <module>
    TC = TotalConnectClient.TotalConnectClient(USERNAME, PASSWORD)
  File "/home/jason/TotalConnectClient.py", line 96, in __init__
    self.authenticate()
  File "/home/jason/TotalConnectClient.py", line 214, in authenticate
    self.populate_details(response)
  File "/home/jason/TotalConnectClient.py", line 305, in populate_details
    self.get_panel_meta_data(location_id)
  File "/home/jason/TotalConnectClient.py", line 435, in get_panel_meta_data
    status = self.locations[location_id].set_status(
  File "/home/jason/TotalConnectClient.py", line 660, in set_status
    if "ZoneInfo" not in data["Zones"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by austinmroczek** [comment]
@jcarr your system is returning data in an unexpected way.  I'd like to look at the exact response you got, which should be in a file in the same directory called `test.log`

Look toward the bottom of the file for a line that includes `GetPanelMetaDataAndFullStatusResponse`.  If I'm correct it should be the very last line in the file.  Please paste the entire line in here.  The line could be thousands of characters long (mine is 6000+), although I'm guessing yours is shorter.

**Comment by jcarr** [comment]
Is this what you were looking for?

```DEBUG:zeep.transports:HTTP Response from https://rs.alarmnet.com/TC21api/tc2.asmx (status: 200):
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><GetPanelMetaDataAndFullStatusResponse xmlns="https://services.alarmnet.com/TC2/"><GetPanelMetaDataAndFullStatusResult><ResultCode>0</ResultCode><ResultData>Success</ResultData><PanelMetadataAndStatus LastUpdatedTimestampTicks="637576412580000000" ConfigurationSequenceNumber="-1" IsInACLoss="false" IsCoverTampered="false" Bell1SupervisionFailure="false" Bell2SupervisionFailure="false" IsInLowBattery="false"><Partitions><PartitionInfo><PartitionID>1</PartitionID><ArmingState>10200</ArmingState><IsAlarmResponded>false</IsAlarmResponded><AlarmTriggerTimeLocalized xsi:nil="true" /></PartitionInfo></Partitions><Zones /><PromptForImportSecuritySettings>true</PromptForImportSecuritySettings></PanelMetadataAndStatus></GetPanelMetaDataAndFullStatusResult></GetPanelMetaDataAndFullStatusResponse></soap:Body></soap:Envelope>```

**Comment by austinmroczek** [comment]
That's what I'm looking for.

This response says your system has zero zones.  Is that right?

**Comment by austinmroczek** [comment]
Your system returning zero zones seems wrong. 

That said, I need to fix the code so it handles zero zones.  It currently handles if no list of zones is returned, but not if an empty list of zones is returned like we see with your system.

**Comment by jcarr** [comment]
I had a security tech replace an older 3G modem with an LTE modem.  I didn't see sensors and ran a sync panel to see if that would help on the day he was here.  I just tried another sync panel and now I have zone output on the info.py script.

**Comment by austinmroczek** [comment]
@jcarr thanks for reporting the issue and helping us improve the code.  I just updated the code to handle this error in the future, and give a log message to users to sync their panel.

Given this is a rare problem, I'm not going to push a new version at the moment. This fix will end up in the next release though.
