### ISSUE TITLE
Adding Partition Support

### ISSUE THREAD

**Issue by rootdet** [craigjmidwinter/total-connect-client#114]
Currently does not support Partitions. I have the new Proa7Plus panel. The library does not even see the partition 2 for me.

**Comment by austinmroczek** [comment]
@rootdet we'll need some help from you in order to add partition support and test the new functions.

I'd like to look at the exact response you get from TotalConnect, which should be in a file called test.log if you've already run the library.  If you don't see that file, follow the Troubleshooting directions to download and execute info.py first.

Look toward the bottom of test.log for a line that includes GetPanelMetaDataAndFullStatusResponse. It should be close to the last line in the file. Please paste the entire line in here. The line could be thousands of characters long (mine is 6000+).

**Comment by rootdet** [comment]
Here is the entire log file for enjoyment

[test.log](https://github.com/craigjmidwinter/total-connect-client/files/6595211/test.log)

**Comment by rootdet** [comment]
Here is the log file. everything sensative should be redacted. 

[test.log](https://github.com/craigjmidwinter/total-connect-client/files/6595224/test.log)

**Comment by austinmroczek** [comment]
Thanks.  I'm now realizing/remembering that we have hard-coded the partition as 1 in multiple places.  This is going to take some time to think through, code and test.  I hope to spend a little time on it this weekend.

Also, I might need to code up a call to https://rs.alarmnet.com/TC21api/tc2.asmx?op=GetPartitionsDetails

I'm not sure what the TotalConnect website allows, but a possible workaround may be to create another user and only allow it to see partition 2.  Then try doing info.py using that username.  Just a guess, and it may not work.

**Comment by austinmroczek** [comment]
OK let's try GetPartitionDetails first.

First download a new file I just made
```console
wget https://raw.githubusercontent.com/austinmroczek/total-connect-client/get_partitions/total_connect_client/live_test_partitions.py
```
Then run it with your deviceID and locationID (which I grabbed from your log file)
```console
python3 live_test_partitions.py username password 4730006 2372119
```
And paste results here

**Comment by rootdet** [comment]
It get this:

`usage:  python3 test.py username password DeviceID LocationID
`

Now if i drop this value to `len(sys.argv) != 5:` it will run and give me this

`


GetPartitionsDetails without partition number



OrderedDict([('ResultCode', -4002),
             ('ResultData', 'The specified location is not valid'),
             ('PartitionsInfoList', None)])
`

I did try to manually edit the file and hard code the variables, and i got the same location is not valid message.  I also tried swapping the numbers in case you had them backwareds and then i got this:

`GetPartitionsDetails without partition number



OrderedDict([('ResultCode', 0),
             ('ResultData', 'Success'),
             ('PartitionsInfoList',
              OrderedDict([('PartitionDetails',
                            [OrderedDict([('PartitionID', 1),
                                          ('ArmingState', 10214),
                                          ('IsAlarmResponded', False),
                                          ('AlarmTriggerTimeLocalized', None),
                                          ('PartitionName', 'Main'),
                                          ('IsStayArmed', False),
                                          ('IsFireEnabled', False),
                                          ('IsCommonEnabled', False),
                                          ('IsLocked', False),
                                          ('IsNewPartition', False),
                                          ('IsNightStayEnabled', 0),
                                          ('ExitDelayTimer', 0)]),
                             OrderedDict([('PartitionID', 2),
                                          ('ArmingState', 10214),
                                          ('IsAlarmResponded', False),
                                          ('AlarmTriggerTimeLocalized', None),
                                          ('PartitionName', 'BSMT-Office'),
                                          ('IsStayArmed', False),
                                          ('IsFireEnabled', False),
                                          ('IsCommonEnabled', False),
                                          ('IsLocked', False),
                                          ('IsNewPartition', False),
                                          ('IsNightStayEnabled', 0),
                                          ('ExitDelayTimer', 0)])])]))])
`

As a note, this particular panel can support up to 4 partitions. I think the max honeywell panels can support is 8 for a hardwire system, but don't 100% quote me on that.

**Comment by austinmroczek** [comment]
Sorry I missed that last change of argv.  

The last thing you did was what I'm looking for.  Will need to absorb and do more code.

Can you arm/disarm single partitions?

**Comment by rootdet** [comment]
On the TC2 website, yes you can (if it has been setup that way). I am setup that way.

**Comment by austinmroczek** [comment]
I'm sure we can figure out how to do that with this library.  I'm scratching my head a bit on how we'd implement that in HA

**Comment by rootdet** [comment]
Right now this library is tied to a polyglot instance for my ISY device. But one baby step at a time :)

**Comment by austinmroczek** [comment]
> 
> 
> @austinmroczek maybe each partition could be a separate alarm entity?

I've started a discussion in the HA devs discord.  I'm hoping another alarm system has already figured this out.

**Comment by austinmroczek** [comment]
@rootdet please download and run the latest code.  I changed a number of files so it may be best to clone my repo at https://github.com/austinmroczek/total-connect-client.git and switch to the `get_partitions` branch.  

Run `info.py` and post results here.  If you see any errors, please include a test.log file too.

I think I have multiple partitions accounted for in most places.  `live_test_partitions.py` is now incorporated into the main code, which is why I'm asking for `info.py` now instead.

**Comment by austinmroczek** [comment]
Looking closer at the SOAP responses, it seems we get an ArmingState for the panel itself, and for each partition.  

I'll need some help to figure out when/how the panel's ArmingState relates to the partitions' ArmingState.  For example, does the panel report `disarmed` when partition 1 is disarmed and partition 2 is `armed`?

**Comment by austinmroczek** [comment]
@rootdet if your able to try the code, I'll have time to work on it more over the weekend

**Comment by austinmroczek** [comment]
@rootdet our first stab at partition support is now in the master code from PR #117.  If you have time please try it.  

You'll need to download all files fromhttps://github.com/craigjmidwinter/total-connect-client/tree/master/total_connect_client 

If you notice any issues please start a new issue.

**Comment by austinmroczek** [comment]
Multi-partition support for Home Assistant is up for review

https://github.com/home-assistant/core/pull/55429
