### ISSUE TITLE
Update ZoneTypeID for ProA7

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#116]
The new ProA7 panel and/or SiX devices have previously unseen ZoneTypeID numbers. We need to figure them out and handle them properly in the code.

Will need help from @rootdet or others with this device.

**Comment by rootdet** [comment]
This will get interesting. The ProA7 has an addon card to called takeover, which allows backwards compatibility with non six technology. So you could be seeing this zonetype in the logs.

**Comment by austinmroczek** [comment]
@rootdet from your log file I see the following that I need help with:

Your zones 3,4,5,6, and 7 report ZoneTypeID 3.  Appears to be a perimeter sensor.  What device is this?

Your zone 8 reports ZoneTypeID 12.  Appears to be a flood sensor.  What device?

Your zone 15 reports ZoneTypeID 10.  What device?

Your zone 1996 reports ZoneTypeID 15.  Appears to be the "Medical" button on the panel. Is that right?

Your zone 1999 reports ZoneTypeID 7.  Appears to be the "Police" button on the panel. Is that right?

We have seen ZoneTypeID 6 with a Lyric panel before, but on your panel it appears to be a button for "Other". Is that right?  Does it call the police?

**Comment by austinmroczek** [comment]
> 
> 
> This will get interesting. The ProA7 has an addon card to called takeover, which allows backwards compatibility with non six technology. So you could be seeing this zonetype in the logs.

I see a number of ZoneTypes that we already knew that I assume are 5800 series devices.

**Comment by austinmroczek** [comment]
FYI you're basically helping me update ZONE_TYPES.md, which I'll then use to update the code.

**Comment by rootdet** [comment]
`Your zones 3,4,5,6, and 7 report ZoneTypeID 3. Appears to be a perimeter sensor. What device is this?`
Device Type: Window
Response Type Perimeter
Takeover Module: Yes
DEvice Model:  Honeywell 5800Mini

`Your zone 8 reports ZoneTypeID 12. Appears to be a flood sensor. What device?`
Device Type: Flood
Response Type: Monitor
Takeover Module: No
Device Model: ProSixFlood

`Your zone 15 reports ZoneTypeID 10. What device?`
Device Type: Other
Response Type: Interior with Delay
Takeover Module: No
Device Model: ProSixMini2
Note: Panle does not support an interior door with delay with device type door.

`Your zone 1996 reports ZoneTypeID 15. Appears to be the "Medical" button on the panel. Is that right?`
Yes, this is on the ProA7Plus Panel

`Your zone 1999 reports ZoneTypeID 7. Appears to be the "Police" button on the panel. Is that right?`
Yes, this is on the ProA7Plus Panel

`We have seen ZoneTypeID 6 with a Lyric panel before, but on your panel it appears to be a button for "Other". Is that right? Does it call the police?`

IF this comes in as zone 998, then it is labeled Silent Alarm. I will give you these:

Zone 995 "Fire"
Device Type: Fire
REsponse type: Fire No Verification

Zone 996 "Medical"
Device Type: Medical
Response type: 24 hour medical

Zone 998 Silent Alarml"
Device Type: silent alarm
Response type: 24 hour silent

Zone 999 "Police"
Device Type: Police
Response type: 24 hour Audible

##

You are also missing the keypad zones, which i currently only have one (adding more sensors/zones soon). These appear to be in the zone id of 8xx. So zone 800 for me is the PROWLTOUCH.

**Comment by dulitz** [comment]
We have two systems using TotalConnect under two different TotalConnect accounts.

System 1:
  zonetype 1: exterior door, delayed alarm
  zonetype 3: exterior door, instant alarm
  zonetype 4: motion
  zonetype 9: smoke or heat detector

System 2:
  zonetype 1: exterior door, delayed alarm
  zonetype 3: exterior door, instant alarm
  zonetype 10: motion
