### ISSUE TITLE
Proposed new version numbering

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#120]
I'd like to change how we do version numbering.  

We've been doing a more traditional 0.xx and slowing incrementing the number. 

I like the approach Home Assistant is doing.  Versions are yyyy.mm.number where yyyy is the year, mm is the month and number is a revision number.

So if we put out a release in July it would be 2021.07, and the first revision would be 2021.07.1

This method lets us avoid artificial decisions of what is a major vs minor release, and the version number also gives you an idea of how recent the code is.

**Comment by uchagani** [comment]
I’m okay with this change but one question that comes to mind is will we do releases every month? If not, are we okay with skipping months where there are no releases?

**Comment by austinmroczek** [comment]
I would just skip

**Comment by austinmroczek** [comment]
Implemented with #117, but I'm not releasing a package yet because there are a few other open items we'll likely fix first.
