### ISSUE TITLE
question: why return False on failure instead of raising exception?

### ISSUE THREAD

**Issue by dulitz** [craigjmidwinter/total-connect-client#121]
This pattern is used throughout and it makes for verbose code with many conditionals, and it also allows failure to be easily ignored.

An example of ignoring failure is that, if authenticate() fails in the constructor, we don't check its return value. And if we did check it to find it failed, all we can really do is... raise an exception, because the constructor has no return value.

An example of verbose code is TotalConnectLocation:get_panel_metadata(), set_arming_state(), and set_status() in the get_partitions branch, which is 62 lines. Using exceptions it would be:

```
    def get_panel_meta_data(self):
        result = self.parent.request(
            f"GetPanelMetaDataAndFullStatusEx_V2(self.token, {self.location_id}, 0, 0, {self._partition_list})"
        )
        self.parent.raise_for_resultcode(result)
        self.set_status(result)
        self.set_arming_state(result)

    def set_arming_state(self, result):
        astate = result.get("ArmingState")
        if not astate:
            raise TotalConnectError("empty ArmingState", result)
        self.arming_state = astate

    def set_status(self, result):
        data = result.get("PanelMetadataAndStatus")
        if not data:
            raise TotalConnectError("empty PanelMetadataAndStatus", result)

        self.ac_loss = data.get("IsInACLoss")
        self.low_battery = data.get("IsInLowBattery")
        self.cover_tampered = data.get("IsCoverTampered")
        self.last_updated_timestamp_ticks = data.get("LastUpdatedTimestampTicks")
        self.configuration_sequence_number = data.get("ConfigurationSequenceNumber")

        self.update_partitions(result)
        self.update_zones(result)
```

And in TotalConnectClient we would have:

```
    def raise_for_resultcode(self, result):
        if result["ResultCode"] != RESULT_SUCCESS:
            raise TotalConnectError("result was not successful", result)
```

I think using exceptions makes the whole thing much more readable. I'm happy to bundle the changes in a pull request, but it would affect absolutely everything so I wanted to get feedback before I did it. Is it a good idea? If it should be done, when should it be done (after the partitions release?).

**Comment by austinmroczek** [comment]
A big reason I started helping with this project (after making my alarm work better in HA) was to learn Python, so I'm sure my code has a lot of room for improvement.  

An exception for authentication failure definitely makes sense. 

I've seen a number of times in the past where the total connect API/service has some sort of hiccup, and returns an empty result, or some element of the expected result is empty, but then it works fine for the next request.  That's why there are so many random checks that some element exists.

My understanding is that raising an exception will halt program execution.  If we do that for any API/service hiccup our code may be halted more than not. 

I think I'll merge the get_partitions into master today, so I suggest waiting, and then just doing a PR against master.

**Comment by dulitz** [comment]
It's a really awesome way to learn Python. That was a good idea.

Exceptions halt execution unless they are caught (e.g. in a try/except/finally block). I haven't looked at HA until 5 minutes ago, but it would be typical for the async task manager to catch exceptions and display user messages accordingly. For example, the HA [Awair integration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/awair/__init__.py#L70) catches the Awair client's exceptions (such as `python_awair.exceptions.AuthError`) and raises corresponding HA exceptions (in this case, `homeassistant.exceptions.ConfigEntryAuthFailed`). There is a catchall "except Exception" at the end, so that if the Awair client raises any other kind of exception, the integration raises `homeassistant.helpers.update_coordinator.UpdateFailed`.

You would do something similar in your integration -- UpdateFailed looks like a good homeassistant exception to raise whenever TotalConnect has a hiccup. For comparison, [this code I wrote](https://github.com/dulitz/porter/blob/main/porter.py#L101) is called while responding to an HTTP request. Any exceptions that propagate up to the HTTP server (i.e. anything we don't catch here) will generate verbose stack traces in the logs and return HTTP 5xx to the web browser. So the entire purpose of that method is to catch all the common exceptions, log them as one-liners, count them (so they can be graphed), and then raise SilentException() which causes an HTTP 503 response without any more logging.

Exceptions enable a coding style where you assume success and then deal with failures only at a higher level (where you will silently retry, or noisily complain, or whatever seems appropriate). This can help methods be more readable, while also ensuring that all exceptions are handled appropriately (where "appropriately" means "crash if no one has thought about what to do for this exception").

Happy to wait, I'll send you a stream of PRs for different things after you merge. :)

**Comment by austinmroczek** [comment]
@dulitz I just merged the partitions PR so please have at it.

**Comment by dulitz** [comment]
On it! Congratulations on the big push. :)

**Comment by dulitz** [comment]
See https://github.com/craigjmidwinter/total-connect-client/pull/124

**Comment by dulitz** [comment]
Merged.
