### ISSUE TITLE
TotalConnectLocation.update_partitions() is wrong

### ISSUE THREAD

**Issue by dulitz** [craigjmidwinter/total-connect-client#125]
`TotalConnectLocation.update_partitions()` is wrong, according to a TODO in the code, and that seems important.

**Comment by austinmroczek** [comment]
Sorry don’t worry about custom-arm.  Not operational yet

Sent from my iPhone

On Jul 18, 2021, at 3:48 PM, Daniel ***@***.***> wrote:

﻿

TotalConnectionLocation.update_partitions() is wrong, according to a FIXME, and that seems important.

TotalConnectZone.is_faulted()has the testif self.zone_type_id == ZONE_TYPE_SECURITY. Should it be if self.is_type_security()` instead?

What is the status of the custom arm stuff?

**Comment by austinmroczek** [comment]
> `TotalConnectZone.is_faulted()` has the test `if self.zone_type_id == ZONE_TYPE_SECURITY`. Should it be `if self.is_type_security()` instead?

If you meant `TotalConnectZone.is_type_button()` has the test then yes, changing to `is_type_security()` makes sense.

**Comment by dulitz** [comment]
I did mean is_type_button(); okay I'll queue up a PR for that.

TotalConnectClient.arm_custom() stands out as the one arm method in the client that is not deprecated. If arm_custom() isn't operational, can we just move it (without deprecation) to Location?

**Comment by dulitz** [comment]
Also, the arming methods on TotalConnectPartition are redundant with those in TotalConnectLocation (which take a partition ID). Redundant methods make things harder for the user of the interface and I think we should remove one set of those. I think the set we should remove are the ones on TotalConnectPartition. Thoughts?

**Comment by austinmroczek** [comment]
In Home Assistant I'm going to end up doing something like:
```python
client = TotalConnectClient(....)
for partition in client.locations[location_id_setting]:
  hass.append(TotalConnectAlarmPanel(partition))
```
`hass.append()` is made up to simplify the example.  That's why I put all those functions in TotalConnectPartition.  Otherwise I'd end up making some calls to TotalConnectLocation and some to TotalConnectPartition for each "TotalConnectAlarmPanel."

If we remove it from TotalConnectLocation, then we can't arm/disarm all partitions at once.  The HA conde wouldn't try to arm/disarm all partitions at once, but I'm thinking we'd want to leave that option for folks.

**Comment by dulitz** [comment]
I agree it should stay in Location -- all partitions is the most common thing people do, and many people don't even know they have a "partition" because they have only one, or only one that they really use.

Thinking about this more, it's not just arm/disarm that concerns me. We're already seeing boilerplate code duplicated between partition and location (all the testing expressions). It's easy for those to get out of sync. It increases the testing and documentation footprint. So I want to spend a minute or 10 making sure.

I think what would make me happy is if we renamed TotalConnectPartition to Armable, and then we had TotalConnectLocation and TotalConnectPartition inherit from Armable. That stops the code duplication, and it also allows things like your AlarmControlPanelEntity to take an Armable and not have to care (in the implementation) whether they are looking at a partition or a location.

Then we would remove the partition argument from the arming methods in TotalConnectLocation, since the way to arm or disarm a partition would be to call the appropriate arming method on the partition object.

**Comment by dulitz** [comment]
What I wrote is confusing. I'll cook something up to illustrate.
