### ISSUE TITLE
unknown result code -30002

### ISSUE THREAD

**Issue by dulitz** [craigjmidwinter/total-connect-client#137]
On the 10th (could have been earlier but my logs start on the 9th), I got:
```
WARNING:total_connect_client.client:unknown result code -30000 with message: None
ERROR:total_connect_client.location:Could not get zone details. ResultCode -30000. ResultData: None
```
And soon after I started getting
```
WARNING:total_connect_client.client:unknown result code -30002 with message: Session ID is not valid.
ERROR:total_connect_client.location:Could not get zone details. ResultCode -30002. ResultData: Session ID is not valid.
```

Refreshing auth makes it work again. It looks like the session ID is expiring, and unless there's an expires value in one of their responses (which we're not parsing), will will just need to catch the error and reauth.

Not hard to add that into the request-reissue loop. I'm happy to send a PR but as the exceptions PR is still pending I don't want to make changes that I'll just have to resolve into the exceptions PR, assuming that you'll merge that at some point.

Let me know how to move forward.

**Comment by austinmroczek** [comment]
I've never seen any sort of expiration time anywhere.  

In `GetPanelMetaData` there is something called `LastUpdatedTimestampTicks` but it doesn't change.  My guess is that's the timehack when panel's configuration was last changed.

PR would be appreciated
