### ISSUE TITLE
investigate alternatives to SOAP

### ISSUE THREAD

**Issue by dulitz** [craigjmidwinter/total-connect-client#154]
SOAP is a super-complex protocol. It's inefficient when used carefully, but it's horrible when used not carefully.

Until I looked into zeep transports just now, I didn't know that we were actually doing multiple round-trips for every single request we issued. Ugh.

I happened to come across [this groovy code](https://raw.githubusercontent.com/bdwilson/SmartThings-TotalConnect-Device/master/SmartThings-TotalConnect-Device.groovy) for TotalConnect. It's ancient. But... it's the same tc2.asmx endpoint we use, and it's visibly the same protocol. _And it's not SOAP._ It looks a lot more REST-like, probably with JSON instead of XML.

I'm curious about trying that instead of SOAP. What do you think?

**Comment by dulitz** [comment]
Have you ever looked at the WSDL file at our endpoint? There's all kinds of wacky stuff in there. Like all the thermostat stuff for Total Connect Comfort. Wild.

**Comment by dulitz** [comment]
Well, I investigated. And indeed there is an _almost_ parallel HTTP POST API. It still returns XML but that would be easy to convert into the same dictionary we have now.

However the latest and greatest operations that handle multiple partitions at once? Those are only available in SOAP. So it seems like the wrong choice to swim against that stream. Sigh.

**Comment by austinmroczek** [comment]
I think we'll consider this done for now
