### ISSUE TITLE
Feature Request - Return Event Log

### ISSUE THREAD

**Issue by zburns** [craigjmidwinter/total-connect-client#157]
Add Arm/Disarm log (or really just list last x number of events from the system).

For example, tracing TotalConnect HTTP requests, I see I can get the information in a JSON string from the following POST command....

https://rs.alarmnet.com/TC2API.TCResource/api/v1/locations/xxxxxxxxxxx/devices/0/Events

Where xxxxxx is the device id and the activity log shows the JSON output as follows....

{"Events":
[{"EventRecordId":39544422147,"EventType":10200,"Event":"Disarmed","Originator":"Zachary Burns","Notice":"","Notes":"","HasNotes":false,"IsLocked":false,"IsHidden":false,"RecDateTimeGMT":"2021-10-06 15:49:07","RecDateLocal":"2021-10-06 11:49:07","RecDateSuffix":"EDT","FilterClass":1,"DeviceId": xxxxxxxxxxx,"EventFilterTypeID":1},
{"EventRecordId":39544419382,"EventType":10203,"Event":"Armed Stay","Originator":"Zachary Burns","Notice":"","Notes":"","HasNotes":false,"IsLocked":false,"IsHidden":false,"RecDateTimeGMT":"2021-10-06 15:49:00","RecDateLocal":"2021-10-06 11:49:00","RecDateSuffix":"EDT","FilterClass":1,"DeviceId": xxxxxxxxxxx,"EventFilterTypeID":1}
]}

Just curious, as it seems like it might be possible, but looks like some extra tokens and different API calls might be required to get to the event data as shown from the following....

https://rs.alarmnet.com/TC2API.TCResource/api/v1/locations/xxxxxxxx/devices/0/Events

**Comment by zburns** [comment]
I did see that, but can't seem to get the date format correct to have it return any results.

I'm really interested in getting the user that armed/disarmed the system and the time that happened.  As we have a bunch of different people that arm/disarm the system.

I'm not sure if the API call you propose returns that information - I'm hoping it does if I can get the date/time format right.

**Comment by dulitz** [comment]
@zburns what formats have you tried? SOAP datetime is typically ISO 8601, e.g.: `2008-10-31T15:07:38.6875000-05:00`

where the trailing timezone offset can be replaced by Z and the fractional seconds ought to be optional as I understand it, or sometimes they are truncated to thousandths of a second (38.687).

**Comment by zburns** [comment]
Well, I'm stumped too......but I found this.....

https://rs.alarmnet.com/TC21api/tc2.asmx/GetLiveEvents

That actually records the time/user/etc.....so works for what I'm doing.  Not sure how I missed this call when looking through the API.

I appreciate all your help!

**Comment by austinmroczek** [comment]
You can join us on discord is you want:  https://discord.gg/mfJfqt3p

https://rs.alarmnet.com/TC21api/tc2.asmx?op=GetEventSummary only requires LocationID and doesn't need any times.
