### ISSUE TITLE
HomeAssistant show status of the Alarm Panel, but doesn't arm or disarm

### ISSUE THREAD

**Issue by rprocha** [craigjmidwinter/total-connect-client#16]
I found the reason for the issue that many were highlighting online...

Inside of the file TotalConnectClient.py file, the methods for ARM and DISARM include a line similar to the one below, with a '-1' in the field of the password. In alarm panels like the Lynx Touch L7000, that doesn't work. if you manually replace the '-1' with your alarm panel pin code, that will work. Obviously you should not include Pins/credentials directly in the code, but this will get you working for now...

Instead of :  response = self.soapClient.service.DisarmSecuritySystem(self.token, location['LocationID'], deviceId, '-1')

Replace with:  response = self.soapClient.service.DisarmSecuritySystem(self.token, location['LocationID'], deviceId, 'INSERT YOUR PANEL PIN HERE')

Again, this is for testing purposes only... in real life, do not put your credentials inside of the code.

**Comment by craigjmidwinter** [comment]
great! thanks! Should be pretty straight-forward to update the library and the home assistant integration to accept an optional parameter. Unfortunately I don't have a lynx panel to test with, but if you make a PR that uses the PIN or -1 if it's not set, I'll merge it in and update the package

**Comment by austinmroczek** [comment]
Is @rprocha working on a PR?  I can help.  Also have a panel to test with.

**Comment by austinmroczek** [comment]
Assuming you like this PR, I have changes ready for the Home Assistant side as well.

**Comment by tomciok7** [comment]
Where can i find TotalConnectClient.py  file in hassio? Or should i make it in custom_components?

**Comment by tomciok7** [comment]
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/alarm_control_panel/totalconnect.py", line 94, in alarm_disarm
    self._client.disarm()
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 264, in disarm
    deviceId = self.get_security_panel_device_id(location)
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 149, in get_security_panel_device_id
    raise Exception('No security panel found')
Exception: No security panel found

I got this error when im trying to disarm, can anyone help me with this?

**Comment by austinmroczek** [comment]
@tomciok7 which panel do you have?  If it's like my L7000 with ILP5 ethernet adapter, it returned a name of "ILP5" which was not accounted for in the original code.  If my pull request is approved it will solve that problem.  If you have a different device returning a different name, it will have to be added to the code.

**Comment by tomciok7** [comment]
I have vista 20p panel, the device in location tc 2.0 is  LTE-XV i dont
know does it matter? But where can i find the TotalConnectClient.py file?
When im going to site_packages there is not homeassistant folder

**Comment by tomciok7** [comment]
I dont have any ethernet port in my panel, just have just lte

**Comment by austinmroczek** [comment]
To find the file, from the command line do:
`find / -name TotalConnectClient.py`

To help with your panel, please do this:
`cd <location from above>
nano test.py`

This creates a new python script called test.py.  Paste the code from the attached file into it:

[test.txt](https://github.com/craigjmidwinter/total-connect-client/files/2363705/test.txt)

Run the script with your TC username and password like this:
`python3 test.py username password`

Paste the result in here so I can see it.  If you don't want to share everything, just give me the DeviceName entries.  Keep in mind there may be multiple items called DeviceName.

**Comment by tomciok7** [comment]
Location from above, you mean the same location where the
TotalConnectClient file is?

**Comment by austinmroczek** [comment]
yes

**Comment by tomciok7** [comment]
i Changed the code in TotalConnectClient.py for the code from your
repository and now i have this:

Traceback (most recent call last):

  File "test.py", line 1, in <module>

    import TotalConnectClient

  File
"/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py",
line 64

    logging.info('Getting session details')

    ^

IndentationError: unexpected indent

sob., 8 wrz 2018 o 17:24 Tomasz Pisarczyk <tomek.pisarczyk7@gmail.com>
napisał(a):

**Comment by austinmroczek** [comment]
'zeep' is installed in the homeassistant environment.  Because you're now testing outside of that (from the command line), you need it installed

Do the following:
`pip install zeep`

Then run again and post the result here:
`python3 test.py username password`

**Comment by tomciok7** [comment]
i got this right know:

  File "test.py", line 1, in <module>

    import TotalConnectClient

  File
"/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py",
line 64

    logging.info('Getting session details')

    ^

IndentationError: unexpected indent

sob., 8 wrz 2018 o 17:34 austinmroczek <notifications@github.com>
napisał(a):

**Comment by austinmroczek** [comment]
Let's try a different way.  I'm going to have you clone my repository which has the fixes already included.  This will put an extra copy of all the code in your home directory so we're not messing with anything running inside homeassistant.

`cd ~`
`git clone https://github.com/austinmroczek/total-connect-client.git`
`cd total-connect-client/total_connect_client`
`python3 test.py username password`

Hopefully you'll get output something like:
--- Devices name(s) ---
ILP5
WiFi DoorBell


If you don't have 'git' installed do:
`sudo apt install git`

**Comment by tomciok7** [comment]
i got same error with missing zeep, also after: pip install zeep

  File "test.py", line 1, in <module>

    import TotalConnectClient

  File
"/Users/Tomek/total-connect-client/total_connect_client/TotalConnectClient.py",
line 1, in <module>

    import zeep

ModuleNotFoundError: No module named 'zeep'




sob., 8 wrz 2018 o 18:03 austinmroczek <notifications@github.com>
napisał(a):

**Comment by tomciok7** [comment]
i did it couple times, but it shows me always the same error

sob., 8 wrz 2018 o 18:24 austinmroczek <notifications@github.com>
napisał(a):

> Do again
> pip install zeep
>
> Sent from my iPhone
>

**Comment by tomciok7** [comment]
Requirement already satisfied: zeep in
/usr/local/lib/python3.6/site-packages

Requirement already satisfied: isodate>=0.5.4 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: defusedxml>=0.4.1 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: attrs>=17.2.0 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: lxml>=3.1.0 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: appdirs>=1.4.0 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: pytz in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: requests>=2.7.0 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: requests-toolbelt>=0.7.1 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: six>=1.9.0 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: cached-property>=1.3.0 in
/usr/local/lib/python3.6/site-packages (from zeep)

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in
/usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)

Requirement already satisfied: urllib3<1.24,>=1.21.1 in
/usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)

Requirement already satisfied: idna<2.8,>=2.5 in
/usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)

Requirement already satisfied: certifi>=2017.4.17 in
/usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)



this is what i have when i pip install zeep

sob., 8 wrz 2018 o 18:27 Tomasz Pisarczyk <tomek.pisarczyk7@gmail.com>
napisał(a):

> i did it couple times, but it shows me always the same error
>
> sob., 8 wrz 2018 o 18:24 austinmroczek <notifications@github.com>
> napisał(a):
>
>> Do again
>> pip install zeep
>>
>> Sent from my iPhone
>>

**Comment by tomciok7** [comment]
ok i got it, pip3 install zeep was good,

now i got this:


--- Devices name(s) ---

LTE-XV

sob., 8 wrz 2018 o 18:29 Tomasz Pisarczyk <tomek.pisarczyk7@gmail.com>
napisał(a):

> Requirement already satisfied: zeep in
> /usr/local/lib/python3.6/site-packages
>
> Requirement already satisfied: isodate>=0.5.4 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: defusedxml>=0.4.1 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: attrs>=17.2.0 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: lxml>=3.1.0 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: appdirs>=1.4.0 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: pytz in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: requests>=2.7.0 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: requests-toolbelt>=0.7.1 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: six>=1.9.0 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: cached-property>=1.3.0 in
> /usr/local/lib/python3.6/site-packages (from zeep)
>
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in
> /usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)
>
> Requirement already satisfied: urllib3<1.24,>=1.21.1 in
> /usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)
>
> Requirement already satisfied: idna<2.8,>=2.5 in
> /usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)
>
> Requirement already satisfied: certifi>=2017.4.17 in
> /usr/local/lib/python3.6/site-packages (from requests>=2.7.0->zeep)
>
>
>
> this is what i have when i pip install zeep
>
> sob., 8 wrz 2018 o 18:27 Tomasz Pisarczyk <tomek.pisarczyk7@gmail.com>
> napisał(a):
>
>> i did it couple times, but it shows me always the same error
>>
>> sob., 8 wrz 2018 o 18:24 austinmroczek <notifications@github.com>
>> napisał(a):
>>
>>> Do again
>>> pip install zeep
>>>
>>> Sent from my iPhone
>>>

**Comment by tomciok7** [comment]
yes it works, re-run test showed :

('DeviceFlags',


'PromptForUserCode=0,PromptForInstallerCode=0,PromptForImportSecuritySettings=0,AllowUserSlotEditing=0,CalCapable=1,CanBeSentToPanel=0,CanArmNightStay=0,CanSupportMultiPartition=0,PartitionCount=0,MaxPartitionCount=3,OnBoardingSupport=0,PartitionAdded=0,DuplicateUserSyncStatus=0'),

                                          ('SecurityPanelTypeID',
None)])])]))])





--- Devices name(s) ---

LTE-XV



do you think this is ok ?

sob., 8 wrz 2018 o 20:20 austinmroczek <notifications@github.com>
napisał(a):

**Comment by austinmroczek** [comment]
Now try to put my code in place of the current code and see if it works inside homeassistant.

Backup the original file just in case:
`cp /usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py ~/TotalConnectClient.py.backup`
Copy my code on top of the existing file:
`cp total-connect-client/total_connect_client/TotalConnectClient.py /usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py`

Restart homeassistant

See if it works

**Comment by tomciok7** [comment]
i got same error in HA, when im trying to python3 test.py username password in
this /usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py
i have error:   File "test.py", line 14

    print('--- all location/system data ---')

    ^

IndentationError: unexpected inden


*but when im trying do the same in *total-connect-client/total_connect_client
*folder, terminal returns my device correct, i really dont know what should
i do now*

niedz., 9 wrz 2018 o 13:59 austinmroczek <notifications@github.com>
napisał(a):

**Comment by tomciok7** [comment]
I put little mesh here i think, i dont know you understand me. So In the
home directory when im trying test.py everything works fine, but when im
trying test.py in this location /usr/local/lib/python3.6/
site-packages/total_connect_client
Terminal return the error, and in HA i have the same error what i had
before „ no security panel found”

Maybe can i update total_connect_client folder with the all new files from
you repository? Not just a TotalConnectClient.py?  Or delete old one and
make new one there? Is it possible ? Or what else can i do?

**Comment by craigjmidwinter** [comment]
This issue with the library should be resolved by #17.
