### ISSUE TITLE
Getting "unknown ZoneType" after Core upgrade

### ISSUE THREAD

**Issue by dinan5** [craigjmidwinter/total-connect-client#165]
Today I updates to core-2021.11.3 and I started getting the following messages.  These are unused zones and I've never had an issue with them before.

Logger: total_connect_client.zone
Source: /usr/local/lib/python3.9/site-packages/total_connect_client/zone.py:195
First occurred: 5:00:33 PM (36 occurrences)
Last logged: 5:04:35 PM

unknown ZoneType 21 in OrderedDict([('PartitionId', 1), ('Batterylevel', -1), ('Signalstrength', -1), ('zoneAdditionalInfo', None), ('ZoneID', 50), ('ZoneStatus', 0), ('ZoneTypeId', 21), ('CanBeBypassed', 0), ('ZoneFlags', None)]): please report at https://github.com/craigjmidwinter/total-connect-client/issues
unknown ZoneType 20 in OrderedDict([('PartitionId', 1), ('Batterylevel', -1), ('Signalstrength', -1), ('zoneAdditionalInfo', None), ('ZoneID', 51), ('ZoneStatus', 0), ('ZoneTypeId', 20), ('CanBeBypassed', 0), ('ZoneFlags', None)]): please report at https://github.com/craigjmidwinter/total-connect-client/issues
unknown ZoneType 22 in OrderedDict([('AlarmTriggerTime', None), ('AlarmTriggerTimeLocalized', None), ('ZoneTypeID', 22), ('DeviceType', -1), ('ZoneID', 49), ('ZoneDescription', ''), ('ZoneStatus', 0), ('PartitionID', 1), ('CanBeBypassed', 0)]): please report at https://github.com/craigjmidwinter/total-connect-client/issues
unknown ZoneType 21 in OrderedDict([('AlarmTriggerTime', None), ('AlarmTriggerTimeLocalized', None), ('ZoneTypeID', 21), ('DeviceType', -1), ('ZoneID', 50), ('ZoneDescription', ''), ('ZoneStatus', 0), ('PartitionID', 1), ('CanBeBypassed', 0)]): please report at https://github.com/craigjmidwinter/total-connect-client/issues
unknown ZoneType 20 in OrderedDict([('AlarmTriggerTime', None), ('AlarmTriggerTimeLocalized', None), ('ZoneTypeID', 20), ('DeviceType', -1), ('ZoneID', 51), ('ZoneDescription', ''), ('ZoneStatus', 0), ('PartitionID', 1), ('CanBeBypassed', 0)]): please report at https://github.com/craigjmidwinter/total-connect-client/issues

**Comment by austinmroczek** [comment]
While they are unused, do you know what they do?  I'd like to add code to handle those ZoneTypes if possible.

Are they associated with individual devices or with buttons on your panel?

**Comment by dinan5** [comment]
Hello - I got the follow from the manual:

Zone Type 20, 21, 22 = Usually only used when programming keyfobs - Advanced Programming

Thank you for the quick response.

**Comment by dinan5** [comment]
This is more specific:

20 = Arm-Stay (RF only)
21 = Arm-Away (RF only)
22 = Disarm (RF only)

From: Stephen Gold
Sent: Saturday, November 13, 2021 9:42 PM
To: craigjmidwinter/total-connect-client ***@***.***>; craigjmidwinter/total-connect-client ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [craigjmidwinter/total-connect-client] Getting "unknown ZoneType" after Core upgrade (Issue #165)

Hello - I got the follow from the manual:

Zone Type 20, 21, 22 = Usually only used when programming keyfobs - Advanced Programming

Thank you for the quick response.

**Comment by austinmroczek** [comment]
What panel type do you have? (I want to look up the manual)

**Comment by dinan5** [comment]
320P1

On Nov 13, 2021, at 23:12, Austin Mroczek ***@***.***> wrote:

﻿

What panel type do you have? (I want to look up the manual)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcraigjmidwinter%2Ftotal-connect-client%2Fissues%2F165%23issuecomment-968202715&data=04%7C01%7C%7C8a7c719c4ca648dfb32308d9a724f04c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724599360102745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=siExlqJ4mZjH0%2FtbZMcS2GdRGgvAyw%2Bmv1uPeczPjBY%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARAH6ECU4LMCVOC4DI3XZ63UL4ZJ3ANCNFSM5H7CWFVQ&data=04%7C01%7C%7C8a7c719c4ca648dfb32308d9a724f04c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724599360112741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9qmRUrcabynNho1A0Kg%2F%2BmRbaBvnTQAZRehTEE%2BUgDA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8a7c719c4ca648dfb32308d9a724f04c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724599360112741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i7xFpbjkOTSrZiVOmmxphj5jvyH7ErQJ4TedEWKSAis%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8a7c719c4ca648dfb32308d9a724f04c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637724599360122735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xju82ztfsfZ79eahtmRRof%2FWW%2Fns3EZRWcPnQNb5GVM%3D&reserved=0>.
