### ISSUE TITLE
Zone Details not supported by your Total Connect Account or Hardwar

### ISSUE THREAD

**Issue by codypet** [craigjmidwinter/total-connect-client#169]
I get the following errors upgrading from 10.6 to 11.5.  It works fine when I revert back to 10.6.  Any ideas how I can resolve this?

Logger: total_connect_client.location
Source: /usr/local/lib/python3.9/site-packages/total_connect_client/location.py:100
First occurred: 12:06:35 AM (5 occurrences)
Last logged: 12:08:35 AM

getting Zone Details is a feature not supported by your Total Connect account or hardware

& 

Config entry 'Total Connect' for totalconnect integration not ready yet: ('FEATURE_NOT_SUPPORTED', OrderedDict([('ResultCode', -120), ('ResultData', 'Feature Not Supported'), ('ZoneStatus', None)])); Retrying in background

& 

Logger: total_connect_client.client
Source: /usr/local/lib/python3.9/site-packages/total_connect_client/client.py:86
First occurred: 12:06:35 AM (5 occurrences)
Last logged: 12:08:35 AM

exception during initial fetch of ###### <--This is the panel ID no.

**Comment by austinmroczek** [comment]
Was there a full Traceback available in the log?  Please post.

**Comment by codypet** [comment]
That's all it gives me weirdly.  Unless there's some other separate location that gives more detailed logs.

**Comment by codypet** [comment]
Any other place aside from the main logs or the supervisor logs that could give me some more information why this may not be working?

**Comment by austinmroczek** [comment]
I assume that in Home Assistant 2021.10.6, you get a similar log message about feature not supported, but things continue to work.  Is that right?

It looks like when re refactored the code we went from noting the error then continuing, to throwing an exception and halting the code.

**Comment by dulitz** [comment]
Yes, I didn't know that we were supposed to work in that case.

We may want to have a new subclass of BadResultCodeError,
FeatureNotSupportedError, and have raise_for_resultcode() raise that. Then
we could easily ignore it in the locations() property getter.

If we did that we should also move the warning message from
get_zone_details() into locations().

**Comment by codypet** [comment]
> I assume that in Home Assistant 2021.10.6, you get a similar log message about feature not supported, but things continue to work. Is that right?
> 
> It looks like when re refactored the code we went from noting the error then continuing, to throwing an exception and halting the code.

Sure enough, you're right.
In 10.6 I get this:
```
Logger: root
Source: /usr/local/lib/python3.9/site-packages/total_connect_client/TotalConnectClient.py:503
First occurred: 1:06:10 PM (1 occurrences)
Last logged: 1:06:10 PM

Getting Zone Details is a feature not supported by your Total Connect account or hardware.
```
But like you said it keeps going and works just fine

**Comment by austinmroczek** [comment]
> We may want to have a new subclass of BadResultCodeError, FeatureNotSupportedError, and have raise_for_resultcode() raise that. Then we could easily ignore it in the locations() property getter.

I think instead I'll just put in an 'else' after the warning and indent the next two lines.  


```python
        if _ResultCode.from_response(result) == _ResultCode.FEATURE_NOT_SUPPORTED:
            LOGGER.warning(
                "getting Zone Details is a feature not supported by "
                "your Total Connect account or hardware"
            )
        else:
            self.parent.raise_for_resultcode(result)
            self._update_zone_details(result)
```

**Comment by codypet** [comment]
That solved it!  Thank you.
