### ISSUE TITLE
Honeywell ProA7Plus Errors

### ISSUE THREAD

**Issue by rtm2017** [craigjmidwinter/total-connect-client#176]
I got some errors in my log, looking at the times and the zones these areas are from I believe they are codes for Zone Tamper and Arming Away with a bypass. Attached are the errors. Let me know if you need any specific information and I can get it for you. 

unknown partition ArmingState 10231
[Arming Away with a bypass.txt](https://github.com/craigjmidwinter/total-connect-client/files/8019223/Arming.Away.with.a.bypass.txt)

and

unknown ZoneStatus 16
[zone in tamper state.txt](https://github.com/craigjmidwinter/total-connect-client/files/8019222/zone.in.tamper.state.txt)

**Comment by austinmroczek** [comment]
Thanks for reporting this.  The ProA7 panels seem to be using some new codes and we haven't found them all yet.  

I'll need to code this up and publish a new release of `total_connect_client`.  Once that's done I can ask for that to be updated in HA.

**Comment by austinmroczek** [comment]
@rtm2017 the two log messages you provided are very close together in time.  Is there any chance that the Zone Tamper could be part of why you got ArmingState 10231 ?  Assuming the zone is no longer in Tamper state, could you try bypassing a zone and doing Arm Away to see if you still get 10231?

On the panel I have (and another I had in the past) I was not allowed to Arm of any kind with a zone in Tamper, it first had to be "cleared".  But we don't know how these new ones work...which is why I ask.

**Comment by rtm2017** [comment]
@austinmroczek 
I took zone 10 and took the cover off the sensor and entered a tamper state. Didn't clear the error and the panel allows me to bypass and arm the system in both Home and Away states. I armed it "Away". While it is armed it reports this error consistently, I'm not sure I can tell from the logs if this is specifically a "Arming" or "Armed" error, but the error persists while the panel is armed and done counting. From the Panels perspective, it warned me there was a tamper, allowed me the option to bypass, counted to 60 and armed successfully "with a bypass". 

[Core errors During Arming Armed.txt](https://github.com/craigjmidwinter/total-connect-client/files/8052336/Core.errors.During.Arming.Armed.txt)

I did it again with Zone 3, put it into tamper > waited for a few minutes errors to show up > Armed it Away with a bypass > waited a few minutes > then disarmed it , this is what that looked like.

[Zone 3 Tamper Arm Away.txt](https://github.com/craigjmidwinter/total-connect-client/files/8052364/Zone.3.Tamper.Arm.Away.txt)

I took some pictures of the panel through the process since it seems like this is a pretty different process/arming state from previous panels and I am not aware of how they worked.

Shows the not ready and is warning me of the tampered sensor
![IMG_20220211_172342](https://user-images.githubusercontent.com/59209856/153688213-0425c589-dedb-4385-8357-de303926bed8.jpg)


![IMG_20220211_172354](https://user-images.githubusercontent.com/59209856/153688219-739ad76b-f8d1-49db-945f-f7405cb6f021.jpg)


![IMG_20220211_172401](https://user-images.githubusercontent.com/59209856/153688249-b7839cb5-3ac8-46d7-8fdb-d6268166e61c.jpg)


![IMG_20220211_172510](https://user-images.githubusercontent.com/59209856/153688250-14c17495-a173-45e4-b9b0-c05d6691068b.jpg)


Hope this helps.

**Comment by austinmroczek** [comment]
Thanks for the detailed response.

It looks like the ProA7 does not return an Arming code, and goes straight from Disarmed to Armed.

Your pictures show Armed Home Bypassed, but I thought the code 10231 was for when you were in Armed Away Bypass.  Does it return 10231 for both Armed Home Bypass and Armed Away Bypass?

**Comment by rtm2017** [comment]
Let me get back to you on that. It appears that on my panel, when I choose any of the options the panel is actually ending up in a "Armed Home" state regardless of option actually selected and bypass or not... so that appears to be a problem I need to reach out with and see why that is. So that explains the confusion between Away and Home I think. 

I am able to get my panel to "Arming Away" and enter a "Armed Away" state using the TC2.0 app and that mode does not appear to cause any errors in the log if a bypass is also present. 

The only mode that causes an error is "Armed Home bypass" causes the 10231 error. 

I plan to reach out to my installer now and find out why my panel does not appear to be respecting my Armed Away selections at the panel and reverting back to Armed Home states while the TC2.0 app works.

**Comment by austinmroczek** [comment]
See #177 because it seems others have the same problem, so I'm guessing it's a bug with the panel, not a setting from your alarm company.
