### ISSUE TITLE
ArmingState 10232

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#177]
As reported by @essvee0 

unknown partition ArmingState 10232 in OrderedDict([('PartitionID', 1), ('ArmingState', 10232), ('IsAlarmResponded', False), ('AlarmTriggerTimeLocalized', None)]):

I also have a new PROA7PLUS system, and the only difference from what is reported above is I am arming in Arm Stay/Home Instant. Thank you!

**Comment by austinmroczek** [comment]
The new ProA7 panels are putting out a lot of new codes.  Someone else reported a second similar issue tonight.

**Comment by austinmroczek** [comment]
@essvee0 could you please try something for me.  Bypass a zone, then do Arm Stay Instant.  Let me know if still gives 10232 or if there is another code (I'm guessing it will give 10233)

**Comment by austinmroczek** [comment]
@essvee0 Thanks.  One more request.  Please try the same thing Arm Stay Bypass (not instant).  Also Arm Night, and Arm Night Bypass.  Hoping we can cover all those results now in one code update.

**Comment by essvee0** [comment]
@austinmroczek, I decided to just try every combination I could come up with! I am not sure how to see a “debug log”, so I can only captured codes if they caused an error. Note also that the 3 “special” Arm Away modes say the name you select as it is arming, but then once armed it changes to say the respective Arm Stay mode (and the status number is as such also). This very well may be a bug in the alarm itself, but I’m not sure!



Arm Away:
? (No error)

Arm Away Bypass:
Actually arms into -> Arm Stay Bypass - 10231

Arm Away Instant:
Actually arms into -> Arm Stay Instant - 10232

Arm Away Instant Bypass:
Actually arms into -> Arm Stay Instant Bypass - 10233



Arm Stay:
? (No error)

Arm Stay Bypass:
10231

Arm Stay Instant:
10232

Arm Stay Instant Bypass:
10233



Arm Night Stay:
? (No error)

Arm Night Stay Bypass:
10219

Arm Night Stay Instant:
10220

Arm Night Stay Instant Bypass:
10221

**Comment by austinmroczek** [comment]
Thanks that's perfect.  I think you and @rtm2017 have found a bug with the ProA7, see #176.

**Comment by austinmroczek** [comment]
Here's the current list of codes, updated from your help above:

Code | Status
------------ | -------------
10200 | Disarmed
10201 | Armed Away
10202 | Armed Away bypass
10203 | Armed Stay
10204 | Armed Stay Bypass
10205 | Armed Away instant
10206 | Armed Away instant bypass
10207 | Alarming.  This code is reported for perimeter sensor devices (doors and windows).  It is also reported for manually pushed buttons on the panel Medical and Police. 
10209 | Armed Stay Instant
10210 | Armed Stay Instant Bypass
10211 | Disarmed bypass
10212 | Alarming Fire/Smoke. This code is reported for smoke detectors.  It is also reported for manually pushed buttons on the panel for Fire.
10213 | Alarming Carbon Monoxide
10214 | Disarmed not ready to arm - zone(s) faulted
10218 | Armed Stay Night
10219 | Armed Night Stay Bypass.  Reported by ProA7 panel.
10220 | Armed Night Stay Instant.  Reported by ProA7 panel.
10221 | Armed Night Stay Instant Bypass.  Reported by ProA7 panel.
10223 | Armed custom bypass
10226 | Armed Stay.  Suddenly reported for Lynx Touch 7000 in November 2021, which previously reported as 10203
10230 | Armed Stay.  Reported by ProA7 panel.
10231 | Armed Away Bypass. Reported by ProA7 panel.
10232 | Armed Stay Instant. Reported by ProA7 panel.
10233 | Armed Stay Instant Bypass. Reported by ProA7 panel.
10307 | Arming
10308 | Disarming

If you (or your significant other) don't mind, testing the 'alarming' codes would be a good idea.  That is when you have tripped the alarm and the siren is blaring (for security, fire and CO).  It's very annoying to test, but I would also hate for it to be an unknown status code, and your planned automations not kick in at a critical time.

**Comment by essvee0** [comment]
You picked a good time to ask... I just put the system into alarm (with Arm Stay Instant, and a perimeter zone faulted), and ran the troubleshooting command, and I see a lot of data, but I cannot find a status code. The closest I see is this:

PARTITION 1 - ***
  ArmingState.ALARMING
  ***

In other armed modes I see a status code on this line, like this:

PARTITION 1 - ***
  ArmingState.ARMED_STAY_10230
***

**Comment by essvee0** [comment]
Ok great, and here is what it says when I push the test button on the smoke detector (with the system disarmed). It seems it already knows that code too. Sorry, I can't test CO because I don't have a detector for it on the alarm.

PARTITION 1 - ***
  ArmingState.ALARMING_FIRE_SMOKE

**Comment by austinmroczek** [comment]
Also ArmingState.ALARMING is our known code for active alarm for perimeter/security/police, it's code 10207.  

For reference the known code are listed at https://github.com/craigjmidwinter/total-connect-client/blob/master/ALARM_STATUS.md

**Comment by austinmroczek** [comment]
> Ok great, and here is what it says when I push the test button on the smoke detector (with the system disarmed). It seems it already knows that code too. Sorry, I can't test CO because I don't have a detector for it on the alarm.
> 
> PARTITION 1 - *** ArmingState.ALARMING_FIRE_SMOKE

We should be good.  Both your security/police and fire/smoke gave the same codes we've already know, so I'd guess that CO will also be the same.
