### ISSUE TITLE
ProA7 Arm Away special ArmingStates

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#179]
The new ProA7 panel has a software bug.  When a user attempts to enter into Arm Away Bypass, Arm Away Instant or Arm Away Instant Bypass, it actually does the Arm Stay version of those modes.  

If/when Honeywell pushes an update and the panel actually enters Arm Away Bypass, etc, we'll need to capture these new ArmingState codes.

See #176 and #177

**Comment by essvee0** [comment]
Note that I just discovered that Arm Away also has the bug. It arms into Arm Stay.

**Comment by austinmroczek** [comment]
And if you're busy reporting this to Honeywell, please point them here.  It would be a lot easier if they just gave us all the code numbers instead of us finding them by trial and error, but we've had a hard time getting their attention.

**Comment by essvee0** [comment]
Yes! Any good tips on how to report a bug directly to honeywell (that they will pay attention to?!)

BTW - massive thanks for supporting this. Ability to arm/disarm with home assistant and connected integrations is so nice!

**Comment by essvee0** [comment]
> And if you're busy reporting this to Honeywell, please point them here. It would be a lot easier if they just gave us all the code numbers instead of us finding them by trial and error, but we've had a hard time getting their attention.

Are they aware of this, and support it? I would be worried that they will attempt to block it somehow.

**Comment by austinmroczek** [comment]
> Are they aware of this, and support it? I would be worried that they will attempt to block it somehow.

They haven't acknowledged the existence of this code as far as I know.  If they are watching their server logs at all they will know, because there are likely at least a few hundred folks using this code just for Home Assistant.  This code was originally based on something for one of the other home automation systems, so there are probably even more "unofficial" users.

The ability of this code to tie TotalConnect into Home Assistant has to be getting them some customers who otherwise would not pay the monthly bill.  So as far as I can see, shutting it down would not be a rational business decision.

**Comment by essvee0** [comment]
Yes, I understand honeywell spun off their alarm systems to the company now called Resideo. I sent an email to my alarm company. They are usually pretty good at following-up, so hopefully they have a channel to Resideo. Luckily this bug would affect anyone using the panel in a totally supported way, so fingers crossed they fix soon. Thanks again.

**Comment by essvee0** [comment]
So I got a reply from my alarm company. This actually makes a lot of sense now:

> Thank you for reaching out! This is actually a feature fairly common in honeywell(resideo) systems and is refereed to as "Auto Arm Stay". The way that Arm Away mode works is that an entry/exit zone must be activated during the exit delay countdown. If it doesn't, the system will simply revert to Arm Stay mode.
If you want your system to go into Arm Away mode with Auto-Stay Arming enabled, simply fault an entry/exit zone while the exit delay period is counting down. This is usually as simple as opening and closing the main entry/exit door for the property.

BTW - this did also mention this mode could be disabled in case anyone cares. For me I'll keep it enabled since it makes sense.

I was in fact not opening a door after putting into the Arm Away modes! I tested again and opened the door each time and all of the codes come up as known codes (ArmingState.ARMED_AWAY, etc), so I think this can be closed and no further code changes are needed!

**Comment by austinmroczek** [comment]
@rtm2017 please look at the above comment and let me know if that's the case for you too

**Comment by rtm2017** [comment]
Wow thanks for that! Yep that seems to be the case for me as well. I can now arm my system in armed away at the panel. 

Let me know if you need any specific testing for the different states! I don't expect any updates to the panel to happen

**Comment by austinmroczek** [comment]
@rtm2017 I'd always welcome folks trying to find more status codes.  If you look at https://github.com/craigjmidwinter/total-connect-client/blob/master/ALARM_STATUS.md you can see what we currently know.  There are a bunch of numbers between the ones we know...but not sure if those numbers were purposefully skipped or if we just haven't found the codes yet.  For example I'd guess there are more codes related to "armed custom".  

I'd also guess there are additional ZoneTypes that ProA7 may report for some sensor types/settings.  See https://github.com/craigjmidwinter/total-connect-client/blob/master/ZONE_TYPES.md  I don't know, but guessing you could change the ZoneType in your panel to various settings and see what happens.
