### ISSUE TITLE
Improved logic for deviceID

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#19]
My system returns two devices, one alarm panel and one "Wifi Doorbell" which is my Skybell.  Since "Wifi Doorbell" isn't in the VALID_DEVICES list it is ignored, but what if someone had two devices that were valid?  

Right now get_security_panel_device_id() will overwrite deviceID if there are multiple valid devices, and return only the last valid deviceID.  

Thoughts on how to fix that?  Arm/disarm all devices at a location?  Force a choice of device when arming/disarming?

I'm guessing it's not a huge priority since few people would have multiple valid devices at one location, but wanted to write it down when I saw it.

**Comment by craigjmidwinter** [comment]
0.20 is now on Pypi! Thanks! Closing this!
