### ISSUE TITLE
Clarify API docs

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#198]
Clarify API docs as discussed near https://github.com/craigjmidwinter/total-connect-client/issues/38#issuecomment-1273951161

**Comment by dulitz** [comment]
FYI I didn't see anything that would address this in #204 but haven't checked all the other commits you merged. Just flagging this in case you still have that in some other client somewhere. :)

**Comment by austinmroczek** [comment]
Maybe I mis-understood what the confusion was about, or what we needed to make more clear.

I thought the issue was knowing if the zone_id was supposed to be an Int or String, so I added the type hints.  If there was something else we can do to clear up confusion (or if I had it wrong) please let me know.

**Comment by dulitz** [comment]
I get it now -- the type hints make sense. Thank you!
