### ISSUE TITLE
Ability to bypass zone in Home Assistant

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#199]
Per discussion near https://github.com/craigjmidwinter/total-connect-client/issues/38#issuecomment-1405439496 

This is more of a Home Assistant issue than total_connect_client, but I want to track this through to completion.

**Comment by austinmroczek** [comment]
@thor0215 would like to discuss your use case and potential HA implementation here.

Tying this concept to the HA user interface is where I'm not sure how to move forward.  

Adding an HA service for `totalconnect_disable_zone` would be pretty easy.  Then you could call it from HA automations.

One thing to keep in mind, as far as I've seen in the API, there is no way to "clear" or enable a zone that has been disabled.  So you could automatically disable a zone via HA, but not clear/enable it.

**Comment by thor0215** [comment]
@austinmroczek that would be great.  So far in my testing if my system is disarmed and using Postman I call the bypass a zone, and then arm the system.  When I disarm the system all zones get cleared.  That is perfect in my testing for what I would want.  This is an example of my pseudo code for an automation.

Arm home
If x is true and automation hasn't been called in last 30 seconds
disarm home
bypass zone
arm home

It would be cool if you could setup various custom predefined arm types, but I think this first step is a great starting point.

**Comment by dulitz** [comment]
@thor0215 Interesting. What are the predefined arm types you would like to have?

**Comment by thor0215** [comment]
@dulitz First off I'm new to Home Assistant, so I currently only have one scenario so a arm_custom_bypass arm type is really all I need at the moment.  That being said I have a couple of thoughts on the user side implementation.  The first and easiest option would be to have a configuration yaml file for total_connect such as

total_connect:
   arm_custom_bypass:
      - binary_sensor.kitchen_glass_break
      - binary_sensor.upstair_bedroom_right_window

My other thought was to allow arm_custom_bypass to kick a script off.  There could be a special call service Bypass Zone action.  Where you could select entities or zones.
total_connect:
   arm_custom_bypass:
      - script.arm_custom_bypass_when_person_X_is_home

The last thought was to make this extensible where you are not just limited to arm_custom_bypass.  The one issue I see with that is how it would integrate with the existing alarm integration.

total_connect:
   arm_custom_bypass:
      - binary_sensor.kitchen_glass_break
      - binary_sensor.upstair_bedroom_right_window
   arm_person_is_home:
      - script.arm_custom_bypass_when_person_X_is_home

**Comment by dulitz** [comment]
You know a lot more about HA than I do -- I don't even use HA. :) It's clearly great and someday I will install it, in my copious free time.

| arm_custom_bypass arm type is really all I need at the moment

Can you be more specific about that? Given the context, I'm imagining that all you need is the ability to configure some zones that will be bypassed, and be able to get that behavior when you press the "arm custom" button. Anything to add to that?

I believe that HA has rules about how configuration is supposed to work. I don't know what those rules are or whether your suggestions of yaml configs are allowed. @austinmroczek will know.

In your example config file, does the arm_custom_bypass key specify a list of zones that *will* be bypassed when the "arm custom" button is pressed, or is it a list of zones to bypass only if they are faulted at the moment the "arm custom" button is pressed?

| Where you could select entities or zones

What are entities?

The "arm person is home" feature is known as "Arm Stay." :) I'm not just trying to be annoying; I don't understand what you intend to do on a person-by-person basis.

An alarm is a pretty heavyweight thing. It never makes sense to set one (or configure one precisely zone-by-zone) unless protection is required. If it goes off and you don't intervene, people with guns will show up at your door and the probability of a person at that location dying has at that point gone from "epsilon" to "delta" if you know what I mean.

So "Away"/"Stay" is not only the high order bit, it's the high order 16 bits. Beyond that it needs to be extremely clear what is happening. So your script could maybe update HA somehow with how it recommends zones to be configured based on ISS ephemeris and who is home, and HA can show a button that will bypass zone 4 if that's what the script recommends. But IMO it would not be good for a button to delegate behind the scenes what zones are going to cause the police to come.

**Comment by thor0215** [comment]
@dulitz It sounds like I need to actually talk to the total connect home assistant integration team.  I did put together a script that HA will kick off based on the situation above and will bypass the sensors I want.  HA needs to enhance its integration.  This total_connect_client actually already has all the code to implement this manually.

**Comment by dulitz** [comment]
Right, I think the client has what is needed, and it's mainly between you and HA about how to do that. @austinmroczek is the person who makes the client do what the integration needs, and he owns the integration as I understand it. I'm curious to see what y'all come up with !

**Comment by austinmroczek** [comment]
Yeah I am the code owner for the `totalconnect` integration in Home Assistant.  I've been hoping that https://github.com/home-assistant/core/pull/73152 would be complete first, but I'll see if I do a different PR to add a bypass service.  The referenced PR also improves awareness of bypass status.

**Comment by austinmroczek** [comment]
The new PR would let you call a service via:
```yaml
service: totalconnect.bypass_zone
target:
  entity_id: alarm_control_panel.<home_name>
data: 
  zone_id: <int>
```

Still need to add tests and docs, but out of time this morning.

**Comment by thor0215** [comment]
@austinmroczek the proposed service call above would be great.  I can do some testing once this feature has been added to HA.

**Comment by austinmroczek** [comment]
@thor0215 so you know I'm going to wait for https://github.com/home-assistant/core/pull/73152 before I add a test for this and submit a PR. 73152 changes the way we handle bypassed status within HA.  If I were to submit 87486 before 73152 is merged, I'll need to adjust code in 73152.  It's a lot less work for me to wait.

If you wanted to try this before that happens, you can copy the code from the `homeassistant/components/totalconnect` folder in https://github.com/home-assistant/core/pull/87486 into a folder called `custom_components/totalconnect` in your config.  Restart HA.

**Comment by thor0215** [comment]
Austin,

I gave this a try and here are my findings.  First, the service call needs
to choose binary_sensor, not alarm_control_panel.  I made the change below
in the services.yaml and then I was able to choose the sensor I wanted to
bypass.

bypass_zone:
  name: Bypass Zone
  description: Bypass a security zone.
  target:
    entity:
      integration: totalconnect
      domain: binary_sensor

[image: image.png]

I don't understand the code well enough to know where to begin to fix the
service call now that I've changed it to a binary sensor instead of the
alarm_control_panel.  For you're reference though, this is what my
binary_sensor looks like:
[image: image.png]

HTH,
Bryan

**Comment by austinmroczek** [comment]
At the moment in HA, the binary sensor is just shows the status of a particular zone, but can't control anything directly. The way the current code works, we need the domain to be alarm_control_panel to be the target for now.  It has a reference to the total_connect_client and can request the bypass.

**Comment by thor0215** [comment]
How would I choose which zone (binary sensor) gets bypassed?

**Comment by austinmroczek** [comment]
I'm about to push an update.  

It will be:

```yaml
service: totalconnect.bypass_zone
data:
  zone_id: 11
target:
  entity_id: alarm_control_panel.home1

```

**Comment by austinmroczek** [comment]
For now you'll have to enter the zone number manually (not pick from list).

**Comment by thor0215** [comment]
Got it, that's fine.  Let me know when it's live and I'll test it again.

I have another question.  I have total connect setup to bypass zone if 
battery low.  That works fine, but that zone will always be bypassed.  
Is that by design?  I would only want the zone to go bypassed when I go 
to arm the system.

**Comment by austinmroczek** [comment]
I made the auto-bypass low battery because at least for me / my system (Lynx Touch 7000) when a zone goes low battery, the panel beeps once per minute until I go press buttons on the physical panel. This always seems to happen in the middle of the night, like 3 or 4 am., usually on a cold winter night when the battery voltage drops below some threshold.  That means I have to get out of bed, go downstairs, push buttons on the panel (which causes more beeping) and then the whole house is awake.

Auto-bypass was meant to stop all that, or at least minimize it to one beep.  It also doesn't work if the zone cannot be bypassed, like a smoke detector (see #202).

**Comment by austinmroczek** [comment]
And the updated code is in https://github.com/home-assistant/core/pull/87486

**Comment by thor0215** [comment]
That makes sense.  I think you're right mine may beep some too, but I 
think only if it's armed and while it's armed the battery goes low.  I 
have a L5100-WIFI and I think once I acknowledge the low battery it 
doesn't keep beeping.  I'll try to test out your latest build sometime 
this week.

Bryan

**Comment by austinmroczek** [comment]
Mine will beep once per minute even if not armed, until a user pushes buttons on panel

**Comment by thor0215** [comment]
Austin,

I did some testing today on the home-assistant/core#87486 build.  I 
created a simple HA script but I'm seeing an issue when I attempt to Arm 
my system.  One thing to note I currently have a zone that has a low 
battery status and that is causing the arming problem.  When 
totalconnect gets that -4504 error, the security system device will go 
to unavailable.  The security system will get armed though, but 
totalconnect HA cannot recover from that -4504 result code.  If I go to 
the cloud total connect site and disarm the system then HA totalconnect 
will become available again.  When I fixed the low battery zone, then 
the bypass zone worked great.

Home Assistant logging:
2023-03-02 10:50:58.028 INFO (MainThread) 
[homeassistant.components.script.test_bypass_zone] Security System - 
Test Bypass Zone: Running script sequence
2023-03-02 10:50:58.028 INFO (MainThread) 
[homeassistant.components.script.test_bypass_zone] Security System - 
Test Bypass Zone: Executing step call service
2023-03-02 10:50:58.525 INFO (SyncWorker_4) 
[total_connect_client.location] DISARMED partitions {'int': [1]} at 247050
2023-03-02 10:50:58.640 INFO (MainThread) 
[homeassistant.components.script.test_bypass_zone] Security System - 
Test Bypass Zone: Executing step call service
2023-03-02 10:50:58.830 INFO (SyncWorker_6) 
[total_connect_client.location] BYPASSED 12 at 247050
2023-03-02 10:50:58.831 INFO (MainThread) 
[homeassistant.components.script.test_bypass_zone] Security System - 
Test Bypass Zone: Executing step call service
2023-03-02 10:50:59.297 INFO (SyncWorker_10) 
[total_connect_client.location] ARMED(ArmType.STAY) partitions {'int': 
[1]} at 247050
2023-03-02 10:51:08.940 ERROR (MainThread) 
[custom_components.totalconnect] Error fetching totalconnect data: 
('unknown result code -4504', OrderedDict([('ResultCode', -4504), 
('ResultData', 'Failed to Bypass Zone')]))

HA Script:
alias: Security System - Test Bypass Zone
sequence:
   - service: alarm_control_panel.alarm_disarm
     data: {}
     target:
       entity_id: alarm_control_panel.thoreson_residence
   - service: totalconnect.bypass_zone
     data:
       zone_id: 12
     target:
       entity_id: alarm_control_panel.thoreson_residence
    - service: totalconnect.bypass_zone
     data:
       zone_id: 11
     target:
       entity_id: alarm_control_panel.thoreson_residence - service: 
alarm_control_panel.alarm_arm_home
     data: {}
     target:
       entity_id: alarm_control_panel.thoreson_residence
mode: single

**Comment by austinmroczek** [comment]
Thanks for continuing to test.  

The bypass issue should be fixed with the [2023.2 release](https://github.com/craigjmidwinter/total-connect-client/releases/tag/2023.2).  See https://github.com/craigjmidwinter/total-connect-client/issues/202. To get 2023.2 into HA you need to update the version in `manifest.json` and restart HA.

**Comment by austinmroczek** [comment]
The PR I was waiting for was finally merged, so now I'll dust this off.

**Comment by thor0215** [comment]
What's the latest status on this feature?

**Comment by austinmroczek** [comment]
Sorry I need to dust this off and submit something

**Comment by austinmroczek** [comment]
Instead of adding a new service, I created Buttons for each bypassable zone, one for the panel for Bypass All and Clear bypass.  Sorry it took more than a year.

**Comment by austinmroczek** [comment]
The new buttons are now in the `dev` branch of HA, which means they should be in the next release.
