### ISSUE TITLE
ZoneStatus not matching reality

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#209]
While working on testing code by bypass_all, I see that the ZoneStatus reported for my window does not match with reality.  The window is open/faulted.  Panel shows it as faulted. TC 2.0 app shows it as faulted.  However, total_connect_client shows it as normal/closed. I verified the zone is not bypassed. 

I did a panel sync.  No change.

Verified the result is in the raw SOAP message, and not some hidden logic flaw in our code.

Verified I get the same result with the same username (because I use a different user for testing, and my "master" user for the app)

I'm hoping this is just some hiccup.

**Comment by austinmroczek** [comment]
Somehow my zones reverted back to "off" in Sensor Activity settings in TotalConnect.  Fixed now.

**Comment by dulitz** [comment]
@austinmroczek could you give a bit more detail here? Was the problem with their SOAP API, or something on our end?

**Comment by austinmroczek** [comment]
I just realized that the only place we mention the need to set "Sensor Activity" is in the HA docs.  Just updated readme with https://github.com/craigjmidwinter/total-connect-client/pull/211
