### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by danlinn** [craigjmidwinter/total-connect-client#21]
Any idea what the alarm going off state is? I never see that in HA. Use case is disarming an alarm when I know someone is there or reacting with more lights and a loud voice telling them the fuzz are on the way.

Thank you for starting this!

**Comment by danlinn** [comment]
Your support is quicker than my alarm company!

I’ll take a stab at testing the API, thanks! My family is gonna love me :D

**Comment by austinmroczek** [comment]
I've been playing around with ZoneStatus a bit.  All based on Lynx Touch 7000.  Not sure if other panels provide different status codes.

Door (perimeter sensor)
0 when closed (normal)
0 when open (panel says Fault)
1 when zone is Bypassed

What's interesting is that TotalConnect2 app on iphone is able to know when a zone is faulted.

I'm guessing we need to focus on ArmingState to solve your question.

**Comment by danlinn** [comment]
That doesn't seem to have any affect in my testing. It's still Armed_stay, right up until I disarm. Alarm panel says Alarm 2 Front Door, so I'm gonna try to look into device specific codes/events, but that's kind of a maze

**Comment by uchagani** [comment]
Fixed by #34
