### ISSUE TITLE
Enable Managing Multiple Locations

### ISSUE THREAD

**Issue by FedgarLurch** [craigjmidwinter/total-connect-client#26]
I am trying to integrate my totalconnect panel, with my home assistant system. I have gotten the implementation to work. But my system has two buildings and I have no idea how to select the second building. 
I have worked with the Home assistant crew, and they directed me over here to pull a feature request. 

Is there any way to select different buildings? 

Thanks!

**Comment by uchagani** [comment]
@FedgarLurch there is a location section in the API( https://github.com/craigjmidwinter/total-connect-client/blob/master/total_connect_client/TotalConnectClient.py#L92)  See if that helps.

**Comment by FedgarLurch** [comment]
Okay, so how would I know what name to use? The app has a human readable name, should I replace the spaces with underscores? 

https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/alarm_control_panel/totalconnect.py

This is the python that we use to pass information along.

**Comment by FedgarLurch** [comment]
@uchagani Ah, yes I do have multiple buildings, each with their own panel. I didnt think there was a provision for it currently hence why I am here. 
Yes I would be happy to hop on Discord, explain in detail, and work with you for testing.

**Comment by austinmroczek** [comment]
I suggest adding an optional location_name at startup, which can be fed by an optional config entry in HA.  It would be similar to how we added the usercode in pull #17.  This would keep everyone's current configuration backwards compatible.

**Comment by FedgarLurch** [comment]
I can see it working with a modified HA component to get it to pass a "location_name" parameter. Does anyone know how the panels handles separate locations? Whether it uses the names or if it has a numerical index we can use? 
I looked through the svcTC2API and it makes sense when I compare it to the TotalConnectClient.py code, im just not sure how to make a call back for different locations/panels/systems. 
Let me know what I can help with and I will be happy to help.

**Comment by austinmroczek** [comment]
get_location_by_location_name() returns the following for me:

OrderedDict([('LocationID', xxxxxx),
             ('LocationName', 'Home'), 
              ....

Where 'xxxxxx' is a 6 digit number.   

The LocationName 'Home' is what I entered in https://totalconnect2.com. 

get_location_by_location_name('Home') works, but using other strings it fails.  

I only have one location so would need @FedgarLurch to try it out.

I would assume the easiest way to do things is modify HA to allow for two instances with unique names.  total-connect-client would need a simple update to __init__ to handle the name passed in from HA.  It may also remove the need to pass location_name=False into every function.

**Comment by austinmroczek** [comment]
To allow for multiple locations I suggest the following big changes:

a) Everywhere we pass location_name, it should instead be locationID.  The reason is that Location Name provided by TotalConnect depends on what the user entered in their account.  It may not be unique.  LocationID is a unique number.

b) Passing the new locationID should no longer be optional for the functions where it currently is.  This removes an unnecessary get_location_by_location_name() call in many places in the code.

c) As far as integrating with Home Assistant, I've already been playing around with a way to change the integration.  We could work it so multiple locations would automatically be recognized, and provide one alarm panel per location.

**Comment by FedgarLurch** [comment]
Thanks everyone for your input. I am available to test. I have very little programming experience with what you are doing, I can program certain industrial platforms but beyond that I am kind of lost. That being said I am interested in learning and helping with whatever I can. I have multiple locations so I am perfectly suited to test changes if someone is willing to walk me through and help explain some of how this works.

**Comment by craigjmidwinter** [comment]
I'm in favour of this change. @uchagani ?

**Comment by uchagani** [comment]
I'm in favour. Seems like a good move forward as long as we aren't
requiring the user to provide a specific location ID and handling it all
ourselves.

We should also consider how to handle situations where a user with multiple
alarm locations only wants to integrate one of them.

**Comment by FedgarLurch** [comment]
I might be speaking out of turn, but would it be possible to have it automatically select the one if there is only one? That way it could be setup that if they have more than one they just have to change it (Already an improvement because in the current system it just selects one and I am unable to change it)

**Comment by craigjmidwinter** [comment]
Yeah, I think what @FedgarLurch mentioned makes sense to me

**Comment by FedgarLurch** [comment]
I am happy to make the changes, if someone can explain to me how the flow of these components actually works, or point me in the direction of a comprehensive walkthrough I will be happy to spend some time trying to get this to work. 

The problem I have is I don't understand which of these components are talking to which, I just don't think I understand the program flow on the level that I would need to to feel comfortable making changes. That being said I am excited to learn if someone has some kind of insight that they can share with me. 

Otherwise if someone else wants to make the changes I will be happy to test them, I will still probably ask a host of questions but atleast with the changes being obvious and highlighted I might be able to glean how things work from that. 

Thanks all!

**Comment by austinmroczek** [comment]
@FedgarLurch one thing you could do is to run test.py and post your output.  It's possible seeing your output before we start coding will help somehow.

From command line, find where test.py lives:
`find / -name TotalConnectClient.py`

Change to that directory:
`cd /path/where/TotalConnectClient/lives`

Run test.py
`python3 test.py your_username 'your_password'`

Wait a few seconds and that should display a bunch of text about your system.  Change anything that includes an ID # into xxxxxx, then copy it here.

**Comment by FedgarLurch** [comment]
Alright, the first steps no problem, when I try to run the test.py I end up with the following error:
`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import TotalConnectClient
  File "/srv/homeassistant/lib/python3.5/site-packages/total_connect_client/TotalConnectClient.py", line 1, in <module>
    import zeep
ImportError: No module named 'zeep'`

Now, I am in the same directory that the TotalConnectClient.py is, and I tried my username / password with every combination of single, double and no quotes. 

Anyone know what a zeep is? I googled this and didnt find anything. 

I opened the test.py with nano and I don't see where it is trying to import anything called zeep.
The script seems pretty straight forward so I am not sure what I am missing (Admittedly I am no expert here)

Thanks! Still feels like progress.

**Comment by austinmroczek** [comment]
You must have a Home Assistant setup that puts everything inside a virtual environment.  Look at https://www.home-assistant.io/docs/installation/virtualenv/.

You'll either need to:
a) Enter the virtual environment, where zeep should already be available.  Likely you need to do:
`cd homeassistant`
`source bin/activate`
Then follow instructions above

b) Install zeep so you can use it directly from your account, which I assume is user "pi"
`sudo pip install zeep`
Then follow instructions above

**Comment by FedgarLurch** [comment]
Okay, so I looked at the options and I was trying to go with option b, but there were errors. 
If I try to go with a, it looks like I am going to end up installing home assistant again, albeit in a virtual environment. Am I understanding the steps properly? The steps don't exactly explain why I am doing things, and I don't like to just blindly run commands.

**Comment by austinmroczek** [comment]
What Home Assistant install method did you use?  HassIO?

You don't need to re-install anything, just find where your virtual environment lives and 'activate' it (for your current shell login) so you can run the test inside it.

I installed hass using the manual install method (https://www.home-assistant.io/docs/installation/raspberry-pi/), the location is 
`/srv/homeassistant/bin/activate`

So to activate I use 
`sudo -u homeassistant -H -s`
`source /srv/homeassistant/bin/activate`

`sudo -u homeassistant -H -s` tells the system to essentially log you in as the homeassistant user.  `man sudo` will tell you more about the command.

`source /srv/homeassistant/bin/activate` activates the python virtual environment where `zeep` should already be installed.  Now you can run the test.

**Comment by FedgarLurch** [comment]
I have a manual install as well. Although not fully manual, It was a hassbian install originally that I reinstalled later. I have been planning on wiping everything out and reinstalling it cleaner since I have been using HA since version .43 and haven't done the housekeeping I should, but that is a different discussion. lol

I was able to correct my zeep issues, back to the problem at hand >
When I ran the test.py, there was a pause, then it returned the following:
```

using username: XXXXX

using password: XXXXX









--- Devices name(s) ---
Security Panel
```

**Comment by austinmroczek** [comment]
I have not fully implemented all of the changes in total_connect_client that I talked about above.  However, I did update Home Assistant so it should support multiple locations now.  I can't test that as I only have one.

If you'd like to test my changes while we're waiting for the next version of Home Assistant here are the steps:

Start in your Home Assistant configuration directory, which for me is:
`cd /home/homeassistant/.homeassistant/`

Make a custom_components directory telling Home Assistant to use a custom version of totalconnect
`mkdir custom_components`
`mkdir custom_components/totalconnect`
`cd custom_components/totalconnect`

Download the two files I changed
`wget https://github.com/austinmroczek/home-assistant/blob/dev/homeassistant/components/totalconnect/__init__.py`
`wget https://github.com/austinmroczek/home-assistant/blob/dev/homeassistant/components/totalconnect/alarm_control_panel.py`

Update your configuration.yaml file
```yaml
totalconnect:
    username: !secret totalconnect_username
    password: !secret totalconnect_password
```
Restart Home Assistant

If something is broken, to undo these changes you need to undo the changes you made to configuration.yaml, then do 
`rm -rf custom_components`
and restart Home Assistant again

If it's working fine, you can keep running the code until you decide to upgrade to Home Assistant 0.95 (assuming my proposed changes are incorporated).

**Comment by FedgarLurch** [comment]
Thanks! I will try them when I get back home and let you know if they work. If so that should go along way to proving them out and getting them incorporated into .95

**Comment by FedgarLurch** [comment]
Update:
So I pulled down the new files, I tested them with no problem. They work just the way the old ones did. The only problem with that is it still doesn't allow me to select between the two of them. 

Here you will see an accepted config. Which everything looks like it should work. 
![image](https://user-images.githubusercontent.com/16086988/59154145-823af800-8a20-11e9-8a5c-64a4a90c3fdd.png)

I even think that the system must be talking to TotalConnect because when I try to use the wrong name for the entity, it gives me an error:
![image](https://user-images.githubusercontent.com/16086988/59154158-b1516980-8a20-11e9-9055-4868f49b0c5f.png)

I am not sure why, it feels like there is still some kind of addressing issue. If I click either of the arm buttons on either of the cards, the "Front Building" is the one that arms. If I manually go arm the shop, neither card reflects those changes. Neither does the States tab. 

The only thing I can think of that I might be doing wrong is I am not 100% it is looking at the custom component version and not the built in Home Assistant version. Is there a way I can make sure it looks at the Custom version?

**Comment by austinmroczek** [comment]
Do you have different alarm control panels in the "unused entities" page?  
`http://your_pi_address:8123/lovelace/hass-unused-entities`

Also please show us what your system shows in the dev-states page.  To get there, click on the Home Assistant menu then click the "< >" button.  Look for the alarm_control_panel entities.  
`http://your_pi_address:8123/dev-state`

**Comment by FedgarLurch** [comment]
No. I disabled the regular totalconnect one. 

![image](https://user-images.githubusercontent.com/16086988/59155279-85db7880-8a3a-11e9-9ade-b7aee6558a6c.png)

```
totalconnect:
    username: !secret tc_username
    password: !secret tc_password
````

**Comment by austinmroczek** [comment]
Should look something like this on the dev states page.  But you will hopefully show two.

![alarm](https://user-images.githubusercontent.com/21700514/59161431-6de61200-8a97-11e9-8644-e6c2ed902228.png)

**Comment by FedgarLurch** [comment]
Can you show me how you have it in your config? Because I pasted the three lines just like this: 
```
totalconnect:
    username: !secret tc_username
    password: !secret tc_password
```
and it doesn't seem to function.

**Comment by austinmroczek** [comment]
a) It may be my fault.  I should have told you to also copy the manifest.json file into the custom_components/totalconnect folder.

`cd custom_components/totalconnect`
`wget https://github.com/austinmroczek/home-assistant/blob/dev/homeassistant/components/totalconnect/manifest.json`

b) Answering your questions
Mine is 
```yaml
totalconnect:
    username: !secret totalconnect_username
    password: !secret totalconnect_password
```

I'm assuming you have tc_username and tc_password defined properly in the secrets.yaml file.

Are there any errors in the Home Assistant error log?

**Comment by FedgarLurch** [comment]
So, new information. For some reason when I was doing `wget` on those files, it was downloading the HTML of the entire page. I have since gone through and created the files locally on my machine (all three) I was hoping that would fix it but no avail.
This is the error I get now: 
![image](https://user-images.githubusercontent.com/16086988/59161711-f2865f80-8a9a-11e9-8d61-915bea3efc5b.png)
Yes, my username and pass were working for the generic one that I have commented out.

**Comment by austinmroczek** [comment]
Sorry those should have been the "raw" links.  Perhaps try removing the three files and re-downloading these to make sure it all came through properly.  Just did it with mine to make sure and it's working.

`wget https://raw.githubusercontent.com/austinmroczek/home-assistant/dev/homeassistant/components/totalconnect/alarm_control_panel.py`
`wget https://raw.githubusercontent.com/austinmroczek/home-assistant/dev/homeassistant/components/totalconnect/__init__.py`
`wget https://raw.githubusercontent.com/austinmroczek/home-assistant/dev/homeassistant/components/totalconnect/manifest.json`

There is definitely a setup function defined in the code.

**Comment by FedgarLurch** [comment]
Hot damn, seems like it is working! 
I can see both locations, and control them individually. Way to go! It looks like the files must not have been downloading properly. 
I do have a few errors I will post here, I don't have the foggiest idea as to what would cause them:
![image](https://user-images.githubusercontent.com/16086988/59162075-c28d8b00-8a9f-11e9-9387-ec4c28a2a1e3.png)

All in all though I think this is a success. I will keep an eye on it, I am going to use these for some automations, I will monitor the system and let you know if I see any problems. 

Let me know if you want me to test any new files. 

Thanks again!

**Comment by austinmroczek** [comment]
@FedgarLurch does everything seem good still?  Can we close this issue?

I think my code will be officially added to HA in 0.97.

**Comment by FedgarLurch** [comment]
All,
Yes I think this can be closed. It has worked relatively flawlessly, with only one hiccup where I had to re-authenticate by just removing and re-adding the module, since then no issues so I would say it can be closed. 

I have another question and will launch a different request for it. 

Thank you all for your help and support. This has been tremendous.
