### ISSUE TITLE
Unable to authenticate with Total Connect

### ISSUE THREAD

**Issue by MaartenProvo** [craigjmidwinter/total-connect-client#27]
Hello

Does this component still work? I'm getting an error 'Unable to authenticate with Total Connect'

Regards

**Comment by uchagani** [comment]
@MaartenProvo yes it works.  I just tested it.  Do you have access to TotalConnect2?

**Comment by kkr16** [comment]
Based on https://github.com/home-assistant/home-assistant/issues/20429 it appears he's trying to login with his TCC (Total Connect Comfort) credentials. 

@craigjmidwinter, if you're OK with it, I can create a PR to add TCC functionality to total-connect-client, but I'll need someone with a TCC connected panel to help with testing..

**Comment by uchagani** [comment]
If it's a different API I don't think it belongs in this library unless the rest of the API is the same and just the authentication is different

**Comment by kkr16** [comment]
It's a different endpoint. I'll compare the WSDLs later today and see if it makes sense to support both. 

But you're right, I think this integration would make more sense on the Honeywell platform, since it already connects to TCC.

**Comment by uchagani** [comment]
@kkr16 `0.25` has been released to pypi

**Comment by uchagani** [comment]
@kkr16 were you able to look into this some more?

**Comment by kkr16** [comment]
@uchagani I don't think this belongs in the TC2 client. We can close this.
