### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when getting zones

### ISSUE THREAD

**Issue by kkr16** [craigjmidwinter/total-connect-client#33]
Reference to HA issue https://github.com/home-assistant/home-assistant/issues/22750

~~It appears older panels such as the ADT Honeywell Lynx does not provide zone info~~ A user has reported panel that did not fully sync the zones to TC2, causing this statement:
https://github.com/craigjmidwinter/total-connect-client/blob/72638680fdcaa848b751f017b56c2b53ddbe7b4a/total_connect_client/TotalConnectClient.py#L64
to fail with error:
`TypeError: 'NoneType' object is not subscriptable`

I'll work on a PR to add some error handling around it and make it fail gracefully if no zone info is returned.

**Comment by austinmroczek** [comment]
Seeing your issue here, I now need to go back and update #28 because I didn't think of panels not providing a response.  

Per https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey  the dict.get() seems to be the way to go.

**Comment by austinmroczek** [comment]
@kkr16 are you working on a PR?  

I'm working on a PR per my comment above.  I can fix this while I'm at it if you don't mind.

**Comment by kkr16** [comment]
> @kkr16 are you working on a PR?
> 
> I'm working on a PR per my comment above. I can fix this while I'm at it if you don't mind.

@austinmroczek 
That would be awesome, please do!
Thanks!
