### ISSUE TITLE
AC Loss and Low Battery not updating

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#41]
The AC Loss and Low Battery status are no longer updating.

Verified by removing the power to my panel.  Total Connect app on IOS reported AC Loss, but total-connect-client didn't.  Same for battery.

**Comment by austinmroczek** [comment]
This seems to be a delay where my panel is slow to update Total Connect for some reason.

**Comment by uchagani** [comment]
It would be great if we could pull the panel directly. There is a "connect
to panel" method and if we could figure out how that works to get info
directly from the panel we can get faster updates.

My panel (lyric controller) specifically has HomeKit functionality so it
can definitely do local access. Just need to figure out how.
