### ISSUE TITLE
Please choose a license for redistribution

### ISSUE THREAD

**Issue by onkelbeh** [craigjmidwinter/total-connect-client#47]
Hi Craig,

first, thanks for your work. I would like to include your integration in my Home Assistant Gentoo overlay, https://github.com/onkelbeh/HomeAssistantRepository/

You have not published a license, not here, and not on pypi, so i am asking for clarification.

According to Gentoo's license guidelines, it is not allowed to redistribute a package without a license (https://devmanual.gentoo.org/general-concepts/licenses/index.html).

Thanks a lot in advance.
 \B.

**Comment by craigjmidwinter** [comment]
@uchagani @austinmroczek do you guys have a preference? I was thinking maybe GNU LGPLv3?

**Comment by austinmroczek** [comment]
I don't have any preference.  

Only thing I would note that Home Assistant uses the Apache 2.0 license...not sure if there's any advantage/disadvantage in being the same.

**Comment by mittelhauser** [comment]
Take it for whatever you want… I’m just a rando monitoring the list (but I have dealt with various OSS licenses a lot) and would tend to favor either

  1.  MIT license – the absolute most simple and permissive license.  Unless you really care about the other stuff, just go with simple (“do anything you want with it ; no guarantees”)
  2.  Apache license – consistent with HA itself and less confusing than the various (L)GPL ones

-Jon

**Comment by uchagani** [comment]
I don't have a preference primarily because I've never really used anything
except MIT license because of its simplicity.

**Comment by onkelbeh** [comment]
In the my [Repository](https://github.com/onkelbeh/HomeAssistantRepository) currently are 799 Packages listet. These are the licenses currently used, perhaps it helps:
```
2x "AGPL-3"
181x "Apache-2.0"
2x "Artistic-2"
127x "BSD"
6x "BSD-2
4x "BSD-2 Unlicense"
7x "BSD-4"
4x "CC0-1.0"
2x "CC-BY-NC-SA-4.0"
2x "ECL-2.0"
8x "EPL-1.0"
135x 'GPL',
  2x "GPL-1"
  26x "GPL-2"
  94x "GPL-3"
  12x "GPL-3+"
4x "LGPL-2+"
8x "LGPL-2.1"
10x "LGPL-3"
4x "LGPL-3+"
576x "MIT"
6x "MPL-2.0"
1x "NEWLIB"
9x "PSF-2"
2x "PSF-2.4"
2x "public-domain"
12x "Unlicense"
5x "ZPL"
```
Beside there are 4 without a license, treated as "all-rights-reserved"

**Comment by craigjmidwinter** [comment]
Committed MIT license directly to master

**Comment by onkelbeh** [comment]
Good choice. Thank you, guys!
