### ISSUE TITLE
Could please somebody file a release for 'pyowlet'?

### ISSUE THREAD

**Issue by onkelbeh** [craigjmidwinter/total-connect-client#48]
Yes, I know, this is the wrong Issue list,
but i cannot file one at https://github.com/craigjmidwinter/pyowlet

I would like to use `pyowlet` in [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).

Therefor I would need a release file in tar.gz format.
Home Assistant currently requires: `pyowlet==1.0.3`

There is one on Pypi, but this is the first one coming only in wheel format, which i cannot use.
As a temporary solution just made a clone of it, and made it a release. [Added it today](https://github.com/onkelbeh/HomeAssistantRepository/commit/f30186ec971570c2e6c40905913e897f063a6adb).

A release on Github would be OK, but a Pypi tar.gz release **would be preferred**, because this could take use of Gentoo's mirror system.

Most of the other integrations do both.

Thanks again, guys.
 \B.

**Comment by craigjmidwinter** [comment]
Issues should be enabled on that repo now. Please open up an issue there. Pyowlet should probably be removed from Home Assistant.

**Comment by onkelbeh** [comment]
OK, will do that.

Can’t tell if it’s worth, just want to have a complete repo for Gentoo with _all_ listed components. Blinded by the sheer enormity of integrations, components and dependent libraries I ignored there’s a lot of crap in that list for now. Cleaning this up is not my province, I'm done when the component compiles, and feel fun. But, since a few day, only problem cases are left. So I added some of these to my account and fixed some issues.

I don’t know if it’s possible to file a pull request with only an added tag.

Anyway, thanks a lot!

  \B.

**Comment by craigjmidwinter** [comment]
Yeah, sorry. There's a bit of a complicated history with this component. Myself and a couple others were working with owlet devs to get that library to a point where it was working in a way that it would be useful but not unnecessarily hammer their api, and then we were going to integrate it into home assistant, but before we could get it there, someone else found the library and implemented the component that currently exists in HASS and then our dialogue with owlet fell apart. As it currently stands, that library no longer points to the api and needs to be updated before it will function again
