### ISSUE TITLE
Auto-bypass low battery zones

### ISSUE THREAD

**Issue by austinmroczek** [craigjmidwinter/total-connect-client#51]
I don't know about everyone else, but my system always waits until the worst possible moment to alert me to have a low battery report.  Usually sometime between 2am and 4am.  My alarm panel then "helpfully" beeps once per minute until I bypass the zone.  By the time I am alert enough to open my phone and bypass the zone, it's beeped 3 or 4 times and everyone in the house is awake - and mad at me.

I'd like total-connect-client to automatically recognize a zone is in low battery state, and immediately bypass it to prevent further beeping.  I'm guessing this would not prevent the first beep, but hopefully prevents any further ones, making my life a little easier.

Yes, this would add a tiny bit of risk in that the burglar / home invader could randomly pick the right night AND right zone to come into my house, and there would be no alarm.

I am willing to code up a solution, but want feedback from others:

a) I know not everyone will want this feature, so it will need to be configurable.  Should it be enabled by default or disabled by default (not changing behavior for existing users)?  I'm leaning toward disabled by default.

b) If total-connect-client were to automatically bypass the zone, I may forget about it by the time I wake up.  I think I would leave any notification/reminders to Home Assistant.  Besides, the panel will also show the zone as bypassed.

c) Any other considerations?

**Comment by uchagani** [comment]
If the feature is implemented I would say disabled by default for sure.
Always err on the side of default behavior.
