### ISSUE TITLE
Please file a release.

### ISSUE THREAD

**Issue by onkelbeh** [craigjmidwinter/total-connect-client#71]
Hi there,

for using your component in [Home Assistant on Gentoo Linux](https://git.edevau.net/onkelbeh/HomeAssistantRepository), I need a release file in tar.gz or zip format. Tagged releases on Github are OK, but a Pypi sdist tar.gz source release would be preferred, because I can automatically merge it and it will use Gentoo’s mirror system. Most of the integrations/components do both. I cannot add packages only available in wheels format.

The current release requested by Home Assistant is `total_connect_client==0.54.1`.

Thanks a lot.

**Comment by craigjmidwinter** [comment]
We can probably look at leveraging the github actions to do this and package updating automatically. If I have some downtime this weekend I'll take a look

**Comment by onkelbeh** [comment]
Thanks. A new Tag in Github would just take seconds.

**Comment by austinmroczek** [comment]
I just updated the tox.ini file so it automatically creates a sdist (tar.gz) file during testing.  We just need to make the github action to push that to pypi.

**Comment by austinmroczek** [comment]
I fought with the Actions thing for a while but can't git it to work.  I posted a new version 0.54.2 that includes tar.gz at https://pypi.org/project/total-connect-client/0.54.2/

**Comment by craigjmidwinter** [comment]
ok thanks @austinmroczek . Going to close this for now
