### ISSUE TITLE
Switch to event driven zone status updates

### ISSUE THREAD

**Issue by trevorcortez** [craigjmidwinter/total-connect-client#86]
I noticed my home-assistant status was delayed 30-60 seconds on average, which in some cases, caused events that occurred between update intervals (for example, an exterior door being opened and closed) to be completely missed.

(Posted here https://github.com/home-assistant/core/issues/37307)

I was looking at the docs here: 
https://rs.alarmnet.com/TC21api/tc2.asmx

and I wondered if a different approach could be:

Use `GetZonesListInStateEx_V1` on launch like it does now to get the current status of all zones.
Then rely on:
> `GetLiveEvents`
> Returns a set of device event records. A maximum of 250 records can be returned per call. The parameter LastEventIdReceived is used to retreive newer records than the ones previously obtained. Entering the most recent event id into this field will return all records that are newer than that record

or 

> `GetAllLiveEvents`
> Returns a set of device event records. A maximum of 250 records can be returned per call. The parameter LastEventIdReceived is used to retreive newer records than the ones previously obtained. Entering the most recent event id into this field will return all records that are newer than that record

…which seems to be more efficient than retrieving status for all zones at all times. Depending on how expensive that method is, it might return faster and be able to handle more frequent polling. Then you'd just need to update the zones that have activity instead of all.

**Comment by austinmroczek** [comment]
For a request we need the following
```txt
    <GetLiveEvents xmlns="https://services.alarmnet.com/TC2/">
      <SessionId>string</SessionId>
      <LocationId>long</LocationId>
      <LastEventIdReceived>long</LastEventIdReceived>
      <MaxRecords>short</MaxRecords>
      <DateFormat>short</DateFormat>
      <TimeFormat>short</TimeFormat>
    </GetLiveEvents>
```
`SessionId` and `LocationId` are known.  We'll have to figure out `DateFormat` and `TimeFormat` by trial and error.  


This response will be a list of EventRecords.
```txt
    <EventRecord>
      <EventRecordId>long</EventRecordId>
      <EventType>long</EventType>
      <Event>string</Event>
      <Originator>string</Originator>
      <Notice>string</Notice>
      <Notes>string</Notes>
      <HasNotes>boolean</HasNotes>
      <IsLocked>boolean</IsLocked>
      <IsHidden>boolean</IsHidden>
      <RecDateTimeGMT>string</RecDateTimeGMT>
      <RecDateLocal>string</RecDateLocal>
      <RecDateSuffix>string</RecDateSuffix>
      <FilterClass>int</FilterClass>
      <DeviceId>long</DeviceId>
      <EventFilterTypeID>long</EventFilterTypeID>
    </EventRecord>
```

At least in other functions, `DeviceId` is the alarm panel itself.  I don't see a field for `ZoneId` so my guess is we'd have to parse the `Event` string or maybe the `Originator` to pull out the ZoneID so it could be associated with the correct zone.  

The thing I'm worried about with this potential method is whether we can still see the Panel Status using this function.  Same thing, we'd likely have to pull it out of the `Event` or other strings.   

To really know we'd need to code it up and see what responses look like.

**Comment by austinmroczek** [comment]
After looking into this a bit, it seems this method would not actually help with the goal of getting faster updates.

In Home Assistant we're using the default polling interval of 30 seconds.  We may be able to reduce that number, but we'd have to figure out at what point we'd end up breaking the TotalConnect server.
